### ISSUE TITLE
Respawn bug.

### ISSUE THREAD

**Issue by NazarbekAld** [PowerNukkitX/PowerNukkitX#1008]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://youtu.be/rBLKozeou3g

### ▶ Steps to Reproduce

1. start the server
2. go to the Nether
3. die

### ✔ Expected Behavior

Teleport to overworld.

### ❌ Actual Behavior

Teleports to nether.

### 📋 Debug information

* PowerNukkit version: 1.19.50-r3
* There's no crashes and no exeptions.

**Comment by smartcmd** [comment]
@CoolLoong

**Comment by CoolLoong** [comment]
try latest version

**Comment by CoolLoong** [comment]
https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/4096539917

**Comment by NazarbekAld** [comment]
Fixed
