### ISSUE TITLE
使用旧版本登入新版本客户端无法正确显示踢出信息

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#1032]
# 🐞 错误汇报
使用旧版本登入新版本客户端无法正确显示踢出信息

### 📸 截图或视频

![Screenshot_2023-02-10-15-14-08-239_com mojang min](https://user-images.githubusercontent.com/22098995/218026730-ffd5d028-f2c9-4f4b-8a23-5b3598e7f57c.jpg)
![VXKR3H85CHXDS`R4G$_L@DT](https://user-images.githubusercontent.com/22098995/218026951-1e2a04d1-4d52-4025-9afc-16804fb5cd68.png)

### ▶ 复现步骤

使用1.19.60-r1PNX 使用1.19.50客户端进服

### ✔ 预期行为

提示踢出信息：客户端已过期

### ❌ 实际行为

提示断开连接

**Comment by smartcmd** [comment]
这个能在纯净端复现吗

**Comment by jlhsr** [comment]
纯净端下 客户端登入会直接卡死

**Comment by smartcmd** [comment]
> 纯净端下 客户端登入会直接卡死

BDS可以复现吗

**Comment by jlhsr** [comment]
![Screenshot_2023-02-10-15-20-27-460_com mojang min](https://user-images.githubusercontent.com/22098995/218028615-5ff95309-8fde-41c4-8106-d3136faaeac2.jpg)
然后手机提示Minecraft无响应

**Comment by jlhsr** [comment]
![Screenshot_2023-02-10-15-27-00-811_com mojang min](https://user-images.githubusercontent.com/22098995/218029083-fb2bf36a-ad17-456b-993b-0818ac44730c.jpg)
BDS

**Comment by Superice666** [comment]
close due to the release of 1.19.62-r1
