### ISSUE TITLE
调试PNXJS时的异常暂停

### ISSUE THREAD

**Issue by CoolLoong** [PowerNukkitX/PowerNukkitX#1054]
# 🐞 错误汇报

调试PNXJS时的异常暂停，默认会暂停运行，进入chrome调试工具提示如下图代码，即使不添加debugger.
### 📸 截图或视频

![image](https://user-images.githubusercontent.com/69153398/220251017-604958f4-497e-4f88-ab89-6e8713bcd945.png)

### ▶ 复现步骤

安装任意PNXJS插件，附加PNX运行参数`--chrome-debug=8888 --js-debug=Test`，启动服务器

### ✔ 预期行为

如果没有添加debugger语句，应该正常运行PNXJS插件

### ❌ 实际行为

即使没有添加debugger语句，也会暂停运行，进入断点

**Comment by Superice666** [comment]
如果不在文件第一行暂停，chrome开发者工具永远都不会正常显示代码。
此问题已经于两年前在上游GraalJS中提出，至今仍未修复。
