### ISSUE TITLE
方块缺失

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#1079]
# 🐞 错误汇报

无法正常使用下面两条命令。

/setblock ~~~ minecraft:stone_slab4

/setblock ~~~ minecraft:double_stone_slab4

在id处提示语法错误

### 📸 截图或视频

![Screenshot_20230307_153807](https://user-images.githubusercontent.com/48203962/223355709-09c0f2fa-6d1a-4e95-96da-e134227082a0.jpg)

**Comment by Superice666** [comment]
转换为其他id的相同方块可以完成此操作吗

**Comment by Mcayear** [comment]
这些都不行

![Screenshot_20230310_091024_edit_9744955254666](https://user-images.githubusercontent.com/48203962/224198185-e3b5814f-431c-4a8a-b284-f86a227dff10.jpg)
![Screenshot_20230310_090953_edit_9782576155433](https://user-images.githubusercontent.com/48203962/224198192-59c7f95c-977c-42d6-8d5a-0c1b6e803731.jpg)

看来是改名为 `minecraft:stone_block_slab4`了。
