### ISSUE TITLE
Smithing table doesn't work

### ISSUE THREAD

**Issue by BlusteryS** [PowerNukkitX/PowerNukkitX#1082]
# 🐞 错误汇报
👉 Smithing table doesn't work

### 📸 截图或视频
![image](https://user-images.githubusercontent.com/52814854/224286205-dd566cf2-77e8-4985-9082-355011c80e6c.png)

### ▶ 复现步骤
1. Place Smithing Table
2. Open Smithing Table
3. Add diamond armor to the first slot
4. Add netherite to the second slot

### ✔ 预期行为
Screenshot from vanilla:
![image](https://user-images.githubusercontent.com/52814854/224286634-10934f51-6e11-4d24-bd72-2cb4d2183f4a.png)

### ❌ 实际行为
✍ Smithing table doesn't work

### 📋 Debug information
[debugpaste-2023-03-10T13.02.35.707+0300.zip](https://github.com/PowerNukkitX/PowerNukkitX/files/10940879/debugpaste-2023-03-10T13.02.35.707%2B0300.zip)

**Comment by CostinDale** [comment]
True, i have same issue!

**Comment by KoshakMineDEV** [comment]
Блюстера Саша, уважаемый вы наш админ NewPlugins, приглашаем вас в наш прекрасный чат RuNukkit, в нем вы узнаете много интересных фактов про себя☺️ https://discord.gg/sYdtKGzP
