### ISSUE TITLE
目前地图生成器的生成的矿洞缺少层次

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#109]
# 🐞 错误汇报

### 📸 截图或视频

原版 
![yuanban](https://user-images.githubusercontent.com/61540722/155870159-e3a0933a-6809-40d4-ab3f-08dbb9c00f48.png)

pnx#107
![pnx](https://user-images.githubusercontent.com/61540722/155870160-f5b0bd1f-708f-4d3d-93c0-6453c00bea70.png)

### ▶ 复现步骤

无地下矿洞那部分投影 有层次感

### ❌ 实际行为

原版对比发现地图缺少层次 地下矿洞那部分投影

### 📋 Debug information

无
### 💢 错误堆栈或崩溃日志

无

### 💬 其他信息

无

**Comment by CivicXFB** [comment]
那黑的地方就是地下洞穴 但我检查了pnx地形绝对没有沟壑

**Comment by lt-name** [comment]
在 https://github.com/PowerNukkitX/PowerNukkitX/pull/1191 优化
