### ISSUE TITLE
pnx-js setTimeout

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#1129]
# 🐞 错误汇报
setTimeout的传参与主流传参不一致

资料：
![image](https://user-images.githubusercontent.com/48203962/230730025-284eee9c-55b6-4cde-ad04-8643887853fb.png)

但在PNX中的逻辑为：
```js
function testFunc(a, b){
   console.log(a + b);
}
setTimeout(testFunc, 1000, 1, 2);// 延时1秒 打印 1001
```

## 💬 其他信息

不知道 `setInterval` 是否有相同问题。

资料：
![image](https://user-images.githubusercontent.com/48203962/230730104-ab0475ad-d91c-4f2b-89a4-e090df5a0b56.png)

### 运行版本
```
> version
23:39:24 [INFO ] 此服务器正在运行 Nukkit 1.19.70-r2 (git-908d32fbf) 「PowerNukkitX」API 版本 1.0.14 的 Minecraft: BE v1.19.70 (协议版本 575)
```

**Comment by Superice666** [comment]
fixed in #1132
