### ISSUE TITLE
玩家無法加入伺服器

### ISSUE THREAD

**Issue by Ootmnt150oO** [PowerNukkitX/PowerNukkitX#113]
# 🐞 错误汇报
伺服器自己創建的world 但是玩家無法加入伺服器

### 📸 截图或视频

![image](https://user-images.githubusercontent.com/60053027/155890950-860f3ae9-5b4e-4c38-8524-cd2d6636c70a.png)

### ▶ 复现步骤

登入伺服器
### ✔ 预期行为

成功加入

### ❌ 实际行为

跳出錯誤 卡在登入畫面

**Comment by Superice666** [comment]
请问替换默认地图是否能解决此问题呢？

**Comment by Ootmnt150oO** [comment]
無法解決

**Comment by Ootmnt150oO** [comment]
![image](https://user-images.githubusercontent.com/60053027/155990963-e32fb844-de78-4d50-8c68-4131fe5820ab.png)

**Comment by Ootmnt150oO** [comment]
linux平台下

**Comment by Superice666** [comment]
此问题我无法在Windows Server 2019、Windows10、Ubuntu 20.04上复现，请问是否可以提供世界地图和配置文件等进一步信息呢？

**Comment by smartcmd** [comment]
> @smartcmd 这或许是你的更改造成的bug，有空记得检查

不应该，getSafeSpawn()方法不会不返回坐标

**Comment by B1n9Y1** [comment]
請檢查你的服務器端口是否開放

**Comment by chencu5958** [comment]
> 請檢查你的服務器端口是否開放

建议你先看看截图里的报错信息和下面的玩家进服信息后再来回复该问题，要真是端口没开放下面是不可能出现玩家进服提示的
