### ISSUE TITLE
Catching fire on edge

### ISSUE THREAD

**Issue by Buddelbubi** [PowerNukkitX/PowerNukkitX#1133]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://youtu.be/YB-TPv7d_J4

### ▶ Steps to Reproduce
![grafik](https://user-images.githubusercontent.com/44944269/230967916-2a7745eb-e4cd-46e4-850a-02917cc70dd1.png)
Build this, and step in the edge where the lava is

### ✔ Expected Behavior

Player shouldn't burn

### ❌ Actual Behavior

Player burns

### 📋 Debug information

* PowerNukkit version: 1.19.70-r2

**Comment by KoshakMineDEV** [comment]
Change label to Confirmed. I have same issue

**Comment by CoolLoong** [comment]
Unable to reproduce

**Comment by CoolLoong** [comment]
![image](https://user-images.githubusercontent.com/69153398/234865919-646d9cb2-45b1-4e7a-91cb-8892eacd0cab.png)

**Comment by CoolLoong** [comment]
version 1.19.80
