### ISSUE TITLE
生存模式下玩家生命值不自然回复问题

### ISSUE THREAD

**Issue by Limo-awa** [PowerNukkitX/PowerNukkitX#1135]
生存模式下的玩家无法在该pnx版本自动回复生命值，（已确保饱食度为8.5格以上）
另外，使用非自然治愈方式（生命回复buff，瞬间治疗buff也无法回复生命）
已排查插件问题
生命回复仅仅在和平模式下才会自动回复
希望能够在下个版本中解决

**Comment by lt-name** [comment]
无法复现问题，请更新到最新核心，然后录制复现视频

**Comment by lt-name** [comment]
长时间未回复，如果您还有此问题请重新发送issue
