### ISSUE TITLE
在控制台使用命令报错

### ISSUE THREAD

**Issue by moyubuaimoyu** [PowerNukkitX/PowerNukkitX#1140]
## Generated Bug Report  PLUGIN ERROR: FALSE ### Expected Behavior  ### Actual Behavior  ### Steps to Reproduce  ### OS and Versions * PowerNukkitX Version: 1.19.70-r2 * Git Commit: git-d890b588a * Java Version: OpenJDK 64-Bit Server VM (17.0.2+8-86) * Host Configuration: | Item | Value | |:----:|:-----:| | Host OS | Windows Server 2022-amd64 [10.0] | | Memory(RAM) | 85.9 GB | | Storage Size | 21.3 GB | | Storage Type | Disk 0:(avail=21.2 GB, total=21.3 GB) | | CPU Type | Intel64 Family 6 Model 62 Stepping 4, GenuineIntel | | CPU Core Count | 28 | ### Crashdump, Backtrace or Other Files ``` java.lang.NullPointerException: Cannot invoke "cn.nukkit.plugin.PluginDescription.getName()" because "this.description" is null 	at cn.nukkit.plugin.PluginBase.getName(PluginBase.java:299) 	at cn.nukkit.scheduler.ServerScheduler.addTask(ServerScheduler.java:255) 	at cn.nukkit.scheduler.ServerScheduler.scheduleTask(ServerScheduler.java:54) 	at cn.nukkit.console.NukkitConsole.runCommand(NukkitConsole.java:36) 	at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:86) 	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:167) 	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140) 	at cn.nukkit.Server$ConsoleThread.run(Server.java:3412) ```

**Comment by CoolLoong** [comment]
给出复现方法

**Comment by lt-name** [comment]
似乎是服务器启动完成之前使用了控制台命令
InternalPlugin还未加载时 控制台尝试用InternalPlugin注册task，从而导致报错
