### ISSUE TITLE
岩浆方块存在伤害范围判定问题

### ISSUE THREAD

**Issue by chencu5958** [PowerNukkitX/PowerNukkitX#115]
# 🐞 错误汇报

如链接里的视频和截图所示，目录为岩浆方块

### 📸 截图或视频

[点此查看](https://pan.baidu.com/s/16vueB_rCrJ-GNBnd4B6PAw?pwd=xcvw) 提取码: xcvw

### 💬 其他信息

测试版本为Terra分支
Git-[3c75121](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1903349641)

**Comment by chencu5958** [comment]
补充：在潜行状态或在岩浆方块上潜行都不会触发扣血机制，取消潜行后依然如此，除非以正常行走状态重新进入，否则无法触发，视频依然在上面的链接中补充

**Comment by Superice666** [comment]
在master上无法复现

**Comment by Superice666** [comment]
由 #178 修复
