### ISSUE TITLE
退出后飞行状态会丢失

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#117]
# 🐞 错误汇报
当玩家在飞行模式退出游戏，重进时会取消飞行。

### ✔ 预期行为
在香草服务器，重新进服仍然是飞行状态

**Comment by Mcayear** [comment]
Uploading SVID_20220306_143808_1.mp4…

**Comment by smartcmd** [comment]
Fixed in PR #873
