### ISSUE TITLE
testBlockHash随机失败

### ISSUE THREAD

**Issue by SuperIceCN** [PowerNukkitX/PowerNukkitX#1197]
# 🐞 错误汇报

BlockAttributesTest#testBlockHash行为在多次测试中不一致，该测试随机失败。

**作为临时补救措施，此测试已禁用。**  

### ▶ 复现步骤

运行此单元测试，在相同环境中有概率成功也有概率失败，表现出不一致的行为，暂未找到规律。  

即使在master上刚添加了此测试的commit中运行，仍然表现出不一致的行为。  

### ✔ 预期行为

单元测试正常通过

### ❌ 实际行为

单元测试失败，NPE。

完全相同的代码，运行多次测试，得到完全不同的结果。
e.g.
https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/5145058115
https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/5145904297
https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/5144880855

Windows PC上暂时无法复现，但Ubuntu云服务器和JitPack CI上也有类似问题。

### 💢 错误堆栈或崩溃日志

org.opentest4j.AssertionFailedError: Failed to hash block: Block[Grass Block] (2:0) ==> expected: not <null>

**Comment by smartcmd** [comment]
迷

**Comment by SuperIceCN** [comment]
暂时关闭，以后遇到新问题再说
