### ISSUE TITLE
荧光墨囊，染料和蜜蜡无法正常对告示牌染色和涂蜡

### ISSUE THREAD

**Issue by yuxibenxi** [PowerNukkitX/PowerNukkitX#1236]
# 🐞 错误汇报
我在写完告示牌后发现只能使用染料对正面染色
还会出现莫名其妙的换行

### 📸 截图或视频
发群里了

### ▶ 复现步骤
如视频

### ✔ 预期行为
如视屏

### ❌ 实际行为
如视频

**Comment by smartcmd** [comment]
已在最新快照修复

**Comment by CoolLoong** [comment]
将在R2修复
