### ISSUE TITLE
The leaves of cherry trees fall off when they come out

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#1243]
# 🐞 错误汇报

### 📸 截图或视频

![`AG~2F38E CFR~I(ZY EK}3](https://github.com/PowerNukkitX/PowerNukkitX/assets/22098995/6df67e44-df14-4684-8b1c-3bc9f9bda5ba)

**Comment by SuperIceCN** [comment]
fixed by #1244
