### ISSUE TITLE
旁观模式下移动速度以及不隐身

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#125]
# 🐞 错误汇报

旁观模式下移动速度以及不隐身

### 📸 截图或视频

![PN96OKO_07MVL GIAZH%XFV](https://user-images.githubusercontent.com/61540722/156866133-a714bb68-d929-478f-9820-6fb7d89e76da.png)

### ▶ 复现步骤

输入/gamemode 3 进入旁观者模式
移动速度非常缓慢

### ✔ 预期行为

对比JE 是隐身状态且移动速度跟创造一样

### ❌ 实际行为

无法隐身且移动速度跟行走无差别

### 📋 Debug information

无

### 💢 错误堆栈或崩溃日志

无

### 💬 其他信息

使用pnx (git-c74f335) 构建

**Comment by Elaina1314** [comment]
实际上 移动慢是因为可以穿墙 没有飞起来 旁观者模式别人是看不到你的.. 并不是bug

**Comment by CivicXFB** [comment]
> 实际上 移动慢是因为可以穿墙 没有飞起来 旁观者模式别人是看不到你的.. 并不是bug

我知道但是对比JE 旁观者模式下 就显得自己没旁观模式

**Comment by chencu5958** [comment]
这个是PN时期就有的问题，已在#40中添加并报告反馈过了

**Comment by TraxTRL** [comment]
This issue has been marked as fixed, however spectator mode still does not work as it does in Minecraft 1.19. You still fly very slowly. Or is that how it should be?
