### ISSUE TITLE
PNX ram usage

### ISSUE THREAD

**Issue by SgatG** [PowerNukkitX/PowerNukkitX#1264]
# 🤷‍♀️ Quesion for PNX

When I run PowernukkitX, Server's ram usage is increased gradually until using almost limit of ram.
If 2GB ram, I run PNX, It starts about 340M first, then increase and increase countinuously.
(If the player join the server, Its usage jump to 860M at once.)

I wonder why it is, also This is just a bug or a natural situation.

### 📋 Debug information

* PowerNukkitX version: 1.20.0-r2 (but I found same situation 1.20.0-r1)
* Debug link: Not Debugged

### 💬 Anything else we should know?

I'm using 4 plugins, but when I disabled all, The ram usage is same.

**Comment by lt-name** [comment]
Did you use PNX-CLI when starting the server?
You may need to adjust the configuration of PNX-CLI to display the memory used by the server if you use

**Comment by SuperIceCN** [comment]
If you're using PNX-CLI with its default configuration, it's how it's designed.
You can manually configure how much memory PNX can use at most, otherwise it will attempt to use all available memory to improve performance by caching more and minimizing memory reclamation.

**Comment by smartcmd** [comment]
-xmx1024m

**Comment by CoolLoong** [comment]
This is a normal. The PNX use cache to optimize performance, and multithreading optimization also requires memory usage. If you don't want to use too much memory, add the above parameters.

**Comment by SgatG** [comment]
Thanks for replying!!
I'm using PNX-CLI, so I will set 1024m and wait a day.

And, I have more question.

When Just turn on server, I wonder if the increase in RAM usage even without doing anything is natural phenomenon.
(At first, it increases at a rate of 3m or 5m, and then the rate of increase gradually decreases. )

I set up 1024m in PNX-CLI.ini, just turn on the server and see.
When Uptime was 7 minutes, ram usage was 760m, and uptime was 9 minutes, ram usage was 900m.

And when uptime was more than 15 minutes, ram usage seemed to stay around 949m.

Lastly, when uptime was about 22 minutes, ram usage The ram usage went to 720 and then started increasing again. 

What I was curious about was that the basic Ram usage was high than I had originally thought.

**Comment by smartcmd** [comment]
It's due to jvm garbage collection
