### ISSUE TITLE
在没有OP权限的情况下依然可以修改服务器的难度

### ISSUE THREAD

**Issue by wood17** [PowerNukkitX/PowerNukkitX#1274]
# 🐞 错误汇报

在没有OP权限的情况下，可以在设置页面，修改服务器难度。
我使用的版本：Minecraft： BE v1.20.0 (协议版本 589) PowerNukkitX API版本 1.0.14 Nukkit 1.20.0-r2 (git-914e68a3e)

### 📸 截图或视频

![Screenshot_2023-06-29-20-52-28-897_com mojang minecraftpe](https://github.com/PowerNukkitX/PowerNukkitX/assets/109504953/3f38c6b4-b5a7-4322-be71-231a10eef1ea)

### ▶ 复现步骤

在服务器中，在没有OP的情况下，进入游戏暂停，进入设置，在游戏页面中，可以随意修改游戏难度。
### ✔ 预期行为

在没有OP的情况下，无法修改游戏难度。

### ❌ 实际行为

在服务器中，在没有OP的情况下，进入游戏暂停，进入设置，在游戏页面中，可以随意修改游戏难度。
### 📋 Debug information

![Screenshot_2023-06-29-22-36-16-128_mark via](https://github.com/PowerNukkitX/PowerNukkitX/assets/109504953/6f42beaa-689d-4185-b1ff-98d964fe201c)
![Screenshot_2023-06-29-22-36-44-104_mark via](https://github.com/PowerNukkitX/PowerNukkitX/assets/109504953/0c523ae8-f490-4572-9c11-84a8bbe85914)

**Comment by smartcmd** [comment]
https://github.com/PowerNukkitX/PowerNukkitX/blob/32b57e6ba4cd3b44d29077dad8007a02e27e7f09/src/main/java/cn/nukkit/network/process/processor/SetDifficultyProcessor.java#L15

检查是否真的修改成功了，这边是有检查的

**Comment by SuperIceCN** [comment]
已确认在master-32b57e6上，没有OP权限无法修改服务端游戏难度。
客户端显示错误问题另行修复。
