### ISSUE TITLE
TextFormat.clean not cleaning

### ISSUE THREAD

**Issue by Sherko231** [PowerNukkitX/PowerNukkitX#1288]
# 🐞 TextFormat.clean() Bug

TextFormat.clean() method doesn't actually clean any color from the new color codes that has been added (like : MATERIAL_COPPER, MATERIAL_DIAMOND, MATERIAL_LAPIS , MINECOIN_GOLD... etc )

### ▶ Steps to Reproduce
just try to use the method on a text that has been colored with one of the new color codes and see the result 

### ✔ Expected Behavior
text should become clean

### ❌ Actual Behavior
TextFormat.clean doesn't clean new color codes ... only the old ones

### 📋 Debug information

* PowerNukkit version: 1.20.0-r2 ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by SuperIceCN** [comment]
Perhaps changing `TextFormat#CLEAN_ PATTERN` can solve this issue, but I have been busy with exams lately and don't have time to write code. Can you help me modify it? thanks

**Comment by Sherko231** [comment]
sure thing ! how can i help ?

**Comment by SuperIceCN** [comment]
1. Fork this repo and clone the new repo in IDEA
2. modify the code, build it using `mvn package`, test your code by replacing the core with your powernukkitx-<version>.jar in target folder
3. if everything is ok, send a pull request to this repo and I'll review and merge your contribution
4. congratulations~ You are one of the PNX developers now!

**Comment by Sherko231** [comment]
oh ok ! 
Thank you I'll try my best !
