### ISSUE TITLE
problem in the list of plugins the plugin is not displayed

### ISSUE THREAD

**Issue by AzaleeX** [PowerNukkitX/PowerNukkitX#1293]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/82237910/9aab0708-64ed-49ec-8003-59851193cbe8)

A problem in the list of plugins the plugin is not displayed even though it is present even when reloading the server this does not change

**🛑 Note that I don't think this happens to everyone.**

### ▶ Steps to Reproduce

1. Run command in console ``/pl``
2. Run command in game ``/pl``
3. Result

**Comment by SuperIceCN** [comment]
Could you pls share your plugin?

**Comment by AzaleeX** [comment]
the problem does not come from powernukkit but from the host

**Comment by Squashhh** [comment]
![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/83670807/555d0810-e703-442d-b5d7-94ef41f58043)
I have the same problem!

**Comment by AzaleeX** [comment]
> ![image](https://user-images.githubusercontent.com/83670807/251444611-555d0810-e703-442d-b5d7-94ef41f58043.png) I have the same problem!

yes after aprodissement of research this comes from the accommodation that you use
