### ISSUE TITLE
Egg Pterodactyl for PNX

### ISSUE THREAD

**Issue by SenseiTarzan** [PowerNukkitX/PowerNukkitX#1296]
I created an egg pterodactyl to simplify the installation of pnx on it.
[egg Ptero](https://github.com/AID-LEARNING/PNX-egg)

**Comment by SenseiTarzan** [comment]
![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/32621158/478134d6-2d9a-4ad4-b798-098437bfe63b)
![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/32621158/2f88ddf0-9479-4b67-9c59-6f7420abf438)

**Comment by SenseiTarzan** [comment]
I use the cli for a system with Debian lite docker

**Comment by AzaleeX** [comment]
Hello @SenseiTarzan, I took into account is check **your eggs** for **PowerNukkitX** if we can take it to put it on our github https://github.com/PowerNukkitX

**Comment by SenseiTarzan** [comment]
I agree, thank you

**Comment by AzaleeX** [comment]
👋 @SenseiTarzan

I will be able to close this from here is the [repositories](https://github.com/PowerNukkitX/PowerNukkitX-Eggs) of your repositories which have been moved to the PowerNukkitX organization 

Thank you for improving PowerNukkitX day by day.
