### ISSUE TITLE
某些区块被重新生成[带有自定义方块]

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#1298]
# 🐞 错误汇报

### 📸 截图或视频

<img width="1280" alt="6b1da8328f0e430e68df85a4da0b1cd3" src="https://github.com/PowerNukkitX/PowerNukkitX/assets/22098995/e863eeed-5f51-4b14-b2f5-a8821338458a">

### 💢 错误堆栈或崩溃日志

<img width="838" alt="5f7ceb61a327fb41b277ee1c2e120fd6" src="https://github.com/PowerNukkitX/PowerNukkitX/assets/22098995/f5406a4c-dd09-41aa-8819-fda68d29ad85">

### 💬 其他信息

![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/22098995/51f7835b-1f85-40ad-9408-c8a5059fba0e)

**Comment by AzaleeX** [comment]
问题是您的名为“Lobby”的世界有一个损坏的块，因此 PowerNukkitX 重新生成损坏的块

**Comment by jlhsr** [comment]
<img width="487" alt="image" src="https://github.com/PowerNukkitX/PowerNukkitX/assets/22098995/72b6a6cc-955e-4320-ad7a-c75fe12d0bcb">

**Comment by AzaleeX** [comment]
你们的世界使用 Anvil 格式的区块来加载，但是一个区块已经在 PowerNukkitX 的世界中损坏，无法找到该区块，因此它会加载一个新的区块，因为你们的区块已经损坏了。

**Comment by AzaleeX** [comment]
> <img alt="image" width="487" src="https://user-images.githubusercontent.com/22098995/251819192-72b6a6cc-955e-4320-ad7a-c75fe12d0bcb.png">

你们的世界使用 Anvil 格式的区块来加载，但是一个区块已经在 PowerNukkitX 的世界中损坏，无法找到该区块，因此它会加载一个新的区块，因为你们的区块已经损坏了。

**Comment by smartcmd** [comment]
You can simply use English :)

**Comment by AzaleeX** [comment]
> You can simply use English :)

yes I think that's what I'm going to do next time because my Chinese isn't too good
