### ISSUE TITLE
很多方块/物品的创造模式物品栏位置不正确

### ISSUE THREAD

**Issue by explorer3039** [PowerNukkitX/PowerNukkitX#1301]
# 🐞 错误汇报

### ▶ 复现步骤

打开创造模式物品栏

### ✔ 预期行为

所有方块/物品的位置正常

### ❌ 实际行为

有些方块/物品位置不正常

**Comment by AzaleeX** [comment]
为了让我们开始解决您的问题，我们需要更多信息，例如照片/视频证明，以及有关来源的更多信息，即您的插件的描述

**Comment by SuperIceCN** [comment]
虽然确实有一部分不太正确，但是也不影响使用，欢迎您发PR来修复此问题

**Comment by CoolLoong** [comment]
不正确是正常的，因为物品方块并没有全部实现完成，这肯定会影响顺序。
