### ISSUE TITLE
The cherry seedling won't plant

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [PowerNukkitX/PowerNukkitX#1308]
# 🐞 I found a bug

The to do sheet said it worked, but it didn't.

### 📸 Screenshots / Videos

https://github.com/PowerNukkitX/PowerNukkitX/assets/68144848/66d45ed2-9c47-416e-8f34-23f163a506f7

### ▶ Steps to Reproduce

1. To hold a cherry sapling in your hands
2. Trying to put him on the ground
3. Figure out what's not working

### ✔ Expected Behavior

A cherry tree sapling is planted on the ground

### ❌ Actual Behavior

Cherry seedling falls out

### 📋 Debug information

* PowerNukkit version: Nukkit 1.20.0-r2 (git-914e68a3e)「 PowerNukkitX」 , version API 1.0.14 for Minecraft: BE v1.20.0 (version protocol 589)
* Debug link: _The server responded with code 500, expected 201_

**Comment by AzaleeX** [comment]
yes I have the same problem but I think I did worse than you but then really worse
https://streamable.com/kj2tc0

**Comment by SuperIceCN** [comment]
Already fixed in #1259
