### ISSUE TITLE
Minecraft 1.20.10 Compatibility 

### ISSUE THREAD

**Issue by eat-sleep-code** [PowerNukkitX/PowerNukkitX#1311]
Minecraft 1.20.10 client was released.  

Attempting to connect to PowerNukkitX 1.20.00-r2  server results in an error of "Could not connect: Outdated server!".

**Comment by AzaleeX** [comment]
> Minecraft 1.20.10 client was released.
> 
> Attempting to connect to PowerNukkitX 1.20.00-r2 server results in an error of "Could not connect: Outdated server!".

yes as it says in the error message is that PowerNukkitX does not yet support 1.20.10 but it will happen soon thanks to this pull request https://github.com/PowerNukkitX/PowerNukkitX/pull/1312
