### ISSUE TITLE
关于 Item 与 ItemBlock 之间的一个错误

### ISSUE THREAD

**Issue by PengLx** [PowerNukkitX/PowerNukkitX#1345]
# 🐞 错误汇报

当你注册了一个物品和这个物品所对应的方块时，
方块注册部分基础信息会被物品覆盖
而如果单纯注册方块不注册物品 则会导致 数据包ID 145 错误。
但是如果要用隐藏方块注册到创造栏中的时候 由于被物品的信息覆盖
这会导致创造栏中多出两个看起来相同 实则物品id不同的物品。

### 📸 截图或视频

![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/35966554/d51b2f91-c818-492b-909c-305bd8974274)
![SAMNFHI4~J6XSR@W7`3T6CK](https://github.com/PowerNukkitX/PowerNukkitX/assets/35966554/7ca3ca33-7c1d-4a01-b0c7-9c3efa7e5441)

**Comment by CoolLoong** [comment]
你不需要注册方块对应的物品
