### ISSUE TITLE
Make 1.17 & 1.18 support please

### ISSUE THREAD

**Issue by whiteralt** [PowerNukkitX/PowerNukkitX#1355]
# I have a question

### It's better said, but it looks more like just an update and that's it

**Comment by AzaleeX** [comment]
Hello @whiteralt,
**@AzaleeX developer for PowerNukkitX**

no PowerNukkitX does not support old protocol something that I myself asked myself but no PowerNukkitX is a software in Java is updated for the latest versions

PowerNukkitX just wants to stay updated on the latest Minecraft releases ✨
