### ISSUE TITLE
剑可以破坏方块

### ISSUE THREAD

**Issue by Pigeon2333** [PowerNukkitX/PowerNukkitX#1360]
# 🐞 错误汇报

### 📸 截图或视频

<img width="1280" alt="image" src="https://github.com/PowerNukkitX/PowerNukkitX/assets/68182691/441dfa50-3f67-4819-9e9f-ef7cac8ce1e0">

### ▶ 复现步骤

在生存或创造模式下用剑挖掘或破坏方块

### ✔ 预期行为

剑无法破坏方块

### ❌ 实际行为

剑可以破坏方块·

### 💬 其他信息

Nukkit 1.20.10-r1 (git-ad87a4367) 「PowerNukkitX」API 版本 1.0.14 的 Minecraft: BE v1.20.10 (协议版本 594)

**Comment by Mcayear** [comment]
属于原版特性

https://github.com/PowerNukkitX/PowerNukkitX/assets/48203962/0d4c1fff-94bc-4593-bcaa-d8295a1a47d4

**Comment by lt-name** [comment]
创造模式不能用剑破坏方块，生存模式可以用剑破坏方块，符合原版特性
