### ISSUE TITLE
穿戴鞘翅从高空垂直落下会卡入地底

### ISSUE THREAD

**Issue by Pigeon2333** [PowerNukkitX/PowerNukkitX#1361]
# 🐞 错误汇报

### 📸 截图或视频

<img width="1280" alt="image" src="https://github.com/PowerNukkitX/PowerNukkitX/assets/68182691/b42a75f0-124f-4e62-abeb-e1899c881d6c">
<img width="1280" alt="image" src="https://github.com/PowerNukkitX/PowerNukkitX/assets/68182691/589f213f-715a-4aca-9537-2a29437c8294">

### ▶ 复现步骤

穿上鞘翅，从一定高度上打开鞘翅垂直向地面飞行·

### ✔ 预期行为

撞向地面后应停止下来

### ❌ 实际行为

撞向地面后卡入了地底且无法通过跳跃等方式恢复正常，鞘翅始终处于打开状态；有玩家称，实际hitbox仍在地面上

### 💬 其他信息

Nukkit 1.20.10-r1 (git-ad87a4367) 「PowerNukkitX」API 版本 1.0.14 的 Minecraft: BE v1.20.10 (协议版本 594)

**Comment by lt-name** [comment]
在 https://github.com/PowerNukkitX/PowerNukkitX/pull/1358 修复，请注意更新版本
