### ISSUE TITLE
Client Upgrade to 1.20.30

### ISSUE THREAD

**Issue by eat-sleep-code** [PowerNukkitX/PowerNukkitX#1380]
Minecraft client has been upgrade to 1.20.30.  This results in users seeing the following error due to client/server version mismatch.

![Screenshot_20230920-134739.png](https://github.com/PowerNukkitX/PowerNukkitX/assets/3846471/5a8cc663-243d-4b20-8447-fe222d337a05)

**Comment by AzaleeX** [comment]
https://github.com/PowerNukkitX/PowerNukkitX/pull/1381
