### ISSUE TITLE
axis bug with log block ?

### ISSUE THREAD

**Issue by Pab450** [PowerNukkitX/PowerNukkitX#1396]
# 🐞 I found a bug | 我找到个BUG

## 📝 Bug Description | BUG描述

when I place the log block in a direction, it is transformed into an update block. the direction of the log blocks seems to be a bit buggy.

## 🔍 Steps to Reproduce | 复现方法

try to place log block in multiple direction to see the bug appear.

## ✅ Expected Behavior | 预期行为

that the log block is placed in the right direction and not transformed into an update block.

## 📸 Screenshots / Video | 截图或视频
<img width="1728" alt="why did u look this alt" src="https://github.com/PowerNukkitX/PowerNukkitX/assets/16840900/8b3a4876-e4b0-44f8-afb1-e56dad6bd703">

**Comment by Verox001** [comment]
Fixed in #1397

**Comment by AzaleeX** [comment]
as @Verox001 says it will soon be fixed
