### ISSUE TITLE
Block BUG

### ISSUE THREAD

**Issue by BramadyaFKS** [PowerNukkitX/PowerNukkitX#1398]
- terracotta block broken
- can't break block (im not lagg)

16:53:15 [WARN ] Unknown block id for the block named minecraft:cyan_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:light_gray_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:red_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:blue_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:green_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:pink_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:yellow_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:light_blue_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:gray_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:magenta_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:white_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:black_terracotta
16:53:15 [WARN ] Unknown block id for the block named minecraft:purple_terracotta
16:53:16 [WARN ] Unknown block id for the block named minecraft:orange_terracotta
16:53:16 [WARN ] Unknown block id for the block named minecraft:brown_terracotta
16:53:16 [WARN ] Unknown block id for the block named minecraft:lime_terracotta

![Screenshot 2023-10-18 234847](https://github.com/PowerNukkitX/PowerNukkitX/assets/90341338/fc0402d7-8446-4d91-bf10-2b472d76d637)
![Screenshot 2023-10-18 235340](https://github.com/PowerNukkitX/PowerNukkitX/assets/90341338/f2d5ade7-4387-4d3e-96c5-30616875ac58)

**Comment by Verox001** [comment]
This is already fixed in the newest Patch:
https://ci.lanink.cn/job/PowerNukkitX/job/master/796/artifact/target/powernukkitx-1.20.30-r1.jar
