### ISSUE TITLE
Gaguhags

### ISSUE THREAD

**Issue by WhiteThunderDev** [PowerNukkitX/PowerNukkitX#1403]
# 🐞 I found a bug | 我找到个BUG

## 🔍 Steps to Reproduce | 复现方法
> Steps to reproduce the behavior / 复现方法:

1. Go to '...' ✍
2. Interact with '....' ✍
3. Perform action '....' ✍
4. See unexpected behavior 😕 ✍

## 💻 OS and versions | 操作系统和PNX版本

* Version: ✍
* Java: OracleJDK/GraalVM/AdoptOpenJDK 
* Java version: 17 
* Game version: Android/iOS/Win10/Xbox/PS4/Switch 

## 💡 Possible Solution | 可能的解决方案

I think that...

## 📝 Logs | 日志

Debug link: ✍ 
Spark link (if relevant) | Spark链接（若可用）: ✍ 

```error
ERROR
```

**Comment by smartcmd** [comment]
？

**Comment by KoshakMineDEV** [comment]
The best issue I've ever seen
