### ISSUE TITLE
Issue With Decorated Pot

### ISSUE THREAD

**Issue by eat-sleep-code** [PowerNukkitX/PowerNukkitX#1408]
I encountered a weird issue with the "Decorated Pot" in the latest version.

If I place a decorated pot, I can see it without a problem.

![Screenshot_20231030-225202.png](https://github.com/PowerNukkitX/PowerNukkitX/assets/3846471/3c02fe0f-5a49-4f6a-8cfe-b387f62611a6)

However, if I then exit the game and come back later I see this.

![Screenshot_20231030-224750.png](https://github.com/PowerNukkitX/PowerNukkitX/assets/3846471/4ce6b8be-b239-47ea-a9d5-4a63c0d4c2f4)

The pot is now invisible.  I can not place another item there.  If I press and hold, I see the break animation for the pot.  Then I can place another item there.

**Comment by KoshakMineDEV** [comment]
MEFRREEX and me also have this error. Change state to confirmed. Tested on latest PNX release, but this bug was before too.

**Comment by KoshakMineDEV** [comment]
Close this issue. Fixed in #1414
