### ISSUE TITLE
feat: Using runtimeId <-> block state hash <-> block state tag mapping instead of compute them

### ISSUE THREAD

**Issue by smartcmd** [PowerNukkitX/PowerNukkitX#1412]
As PNX doesn't (and shouldn't) update its block properties to the latest version, we cannot build the block state tag & hash easily

The current impletation is **too** complex and hard to maintain, and it would be much easier if we can just using an runtimeId <-> block state hash <-> block state tag bi mapping (block state runtime id is easy to get in pnx)

The shortcoming is that we must update the mapping if block palette is changed (After a new MCBE version is released), otherwise the whole system will break. But compare to the current impletation, this shortcoming can be ignored

**Comment by Verox001** [comment]
Isn't this basically the implementation from NukkitX?
