### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by angga7togk** [PowerNukkitX/PowerNukkitX#1421]
why when I enter my minecraft server crashes / force closes, I try to tell my friend to log in too, the console displays the message "logged out due to Timed out"

**Comment by Verox001** [comment]
Can you please provide the detailed logs of when your server crashes?

**Comment by smartcmd** [comment]
?

**Comment by angga7togk** [comment]
> Bisakah Anda memberikan log terperinci saat server Anda mogok?

there are no logs at all, like this on my server it runs and loads chunks for a long time, then it crashes / force closes, then I can't join and the time out message appears on the console, but sometimes it can enter

**Comment by smartcmd** [comment]
At least we need your server log, otherwise we can't determine the problem.

**Comment by angga7togk** [comment]
it's finished, this problem was in v1.20.40, after I updated my minecraft to v1.20.41 nothing happened
