### ISSUE TITLE
Please deban me in discord PowerNukkitX

### ISSUE THREAD

**Issue by AzaleeX** [PowerNukkitX/PowerNukkitX#1470]
My name is **Azalee**, and I am currently interested in joining the **PowerNukkitX** team as a contributing member. However, I recently realized that I have been banned from the **PowerNukkitX** Discord server without knowing the exact reason for the ban.

I'm fascinated by the idea of contributing to such a dynamic and innovative project, and I'm convinced that my software skills will be a great asset.

I'm talking about my Symply software, of course.
https://github.com/SymplyX/Symply
website: https://symplymc.com

Thank you for taking the time to consider my troubleshooting request. I am willing to cooperate fully to resolve this situation in a positive manner.

**Comment by CoolLoong** [comment]
discord DM me
