### ISSUE TITLE
Can't start server with error "Unrecognized VM option 'EnableJVMCI'"

### ISSUE THREAD

**Issue by Kx-Y** [PowerNukkitX/PowerNukkitX#1490]
输出:
root@localhost:/opt/pnx# java -jar ./PNX.jar
16:49:31 [INFO ] 使用的JVM：OpenJDK Server VM
16:49:31 [INFO ] 使用的PNX核心：1.20.50-r1 - 777d7b32a
Unrecognized VM option 'EnableJVMCI'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
16:49:31 [INFO ] 请在10s内键入回车以停止重启...

系统：Ubuntu bionic（在deploy linux中运行） 
java：openjdk17.0.7
cpu：麒麟920 （armv7）

**Comment by CoolLoong** [comment]
Issues for older versions of PNX are no longer accepted here,please go to
https://github.com/PowerNukkitX/PowerNukkitX-Legacy
