### ISSUE TITLE
Server dying due to Lunar Hack

### ISSUE THREAD

**Issue by joaosvc** [PowerNukkitX/PowerNukkitX#1520]
The Lunar Client, available on the PlayStore, which consists of a server proxy system, is causing crashes on several servers, the problem consists of enabling the nuke with a high value and break a block, the problem has already been fixed in PocketMine, I ask that the PowerNukkitX developers resolve it as well,  Thank you very much in advance.

**Comment by AzaleeX** [comment]
Hello @joaosvc,

I understand that there is an issue with the nuke on your "Lunar Client" on the PlayStore, but without a video or screenshot, we cannot take any action.
