### ISSUE TITLE
Loading worlds Chunk

### ISSUE THREAD

**Issue by AzaleeX** [PowerNukkitX/PowerNukkitX#1521]
The loading of worlds is very problematic on **PowerNukkitX**. For instance, when **teleporting a player** to another world, it's possible for them to `pass through blocks`. Moreover, I have the impression that this issue stems from the **`chunk loading process`** taking far too long, resulting in us clipping through the map or getting stuck within blocks.

*_I haven't studied the case properly enough to be able to solve this problem._

https://streamable.com/otjdqm

**Comment by AzaleeX** [comment]
https://streamable.com/otjdqm

**Comment by CoolLoong** [comment]
What's wrong with that? chunk take time to load Unless it has been loaded before

**Comment by AzaleeX** [comment]
it's loaded because I Server.getInstance().loadLevel("name level"), but that doesn't change anything, 2x2 chunk would have to be loaded at the place where the player spawns from base

**Comment by CoolLoong** [comment]
I don't know what you mean.

**Comment by AzaleeX** [comment]
Load the Chucks or the player will spawn
