### ISSUE TITLE
[Repuest]Update Version

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [PowerNukkitX/PowerNukkitX#1523]
plz update server core to ver. 1.20.62 (the lastest Release build is v1.20.50)
请更新服务端到v1.20.62，辛苦咯

**Comment by AzaleeX** [comment]
**Hello** dear @xiaoyueyoqwq,

The update of **PowerNukkitX** to support version **1.20.62** as you say is already out, it to download the version of **PNX 2 (Experimental)** but if you wish I will try to update the version for **PNX version lastest**.

**Comment by xiaoyueyoqwq** [comment]
> **Hello** dear @xiaoyueyoqwq,
> 
> The update of **PowerNukkitX** to support version **1.20.62** as you say is already out, it to download the version of **PNX 2 (Experimental)** but if you wish I will try to update the version for **PNX version lastest**.
> 

Okay, I'll try what you said
And thanks for your reply :-P

**Comment by AzaleeX** [comment]
> > **Hello** dear @xiaoyueyoqwq,
> > The update of **PowerNukkitX** to support version **1.20.62** as you say is already out, it to download the version of **PNX 2 (Experimental)** but if you wish I will try to update the version for **PNX version lastest**.
> 
> Okay, I'll try what you said And thanks for your reply :-P

No problem, the only problem is that **PNX 2 is experimental.**

**Comment by AzaleeX** [comment]
https://www.youtube.com/watch?v=vayOlDEo3tw

**Comment by AzaleeX** [comment]
> > > > **Hello** dear @xiaoyueyoqwq,
> > > > The update of **PowerNukkitX** to support version **1.20.62** as you say is already out, it to download the version of **PNX 2 (Experimental)** but if you wish I will try to update the version for **PNX version lastest**.
> > > 
> > > 
> > > Okay, I'll try what you said And thanks for your reply :-P
> > 
> > 
> > No problem, the only problem is that **PNX 2 is experimental.**
> 
> Okay I got it, if you want to close this thread just do it Or you can keep it until you finish the release PNX update

PNX 2 can be used

**Comment by lt-name** [comment]
可以下载快照版本，PNX2的正式版本会等稳定后再发布
PNX1 https://ci.lanink.cn/view/Nukkit/job/PowerNukkitX/job/Legacy/
PNX2 https://ci.lanink.cn/view/Nukkit/job/PowerNukkitX/job/master/
