### ISSUE TITLE
[CRASH] Terra crash server on 1.20.6-rc1

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [PowerNukkitX/PowerNukkitX#1524]
This is crash logs: https://paste.ubuntu.com/p/QhVBmxcFg4/
I think this is a bug on PowerNukkitX, I've tried to move the configuration files needed for Terra to generate worlds out of nukkit.yml, but even without Terra taking over Vanilla generating worlds, the server still has crashes

**Comment by n15421** [comment]
https://github.com/PowerNukkitX/PowerNukkitX/issues/1501

**Comment by AzaleeX** [comment]
fix https://github.com/PowerNukkitX/PowerNukkitX/commit/ec813528f6e898ec3d98b5b211588b38652daad8
