### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by eat-sleep-code** [PowerNukkitX/PowerNukkitX#1550]
### Describe the bug

Installation method requires login to github.    Makes scripting installs and updates from a bash program difficult.   Please create releases as part of the build process.    These can be marked as pre-release, but at least they would be accessible via scripting.

### To Reproduce

Attempt to download an artifact using curl / wget will fail due to not being logged in from script.

### Expected behavior

Artifacts should create releases.

**Comment by CoolLoong** [comment]
I cannot create a pre release for every commit, which is obviously impossible.And, I'm not ready to release now.

**Comment by CoolLoong** [comment]
I cannot create a pre release for every commit, which is obviously impossible.And, I'm not ready to release now.
