### ISSUE TITLE
[Bug]: CLI collide with devkit

### ISSUE THREAD

**Issue by RomaGly55Creations** [PowerNukkitX/PowerNukkitX#1577]
### Describe the bug

[ INFO ] Using JVM: Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 22.0.1+8.11
[ INFO ] Using PNX core: 2.0.0-SNAPSHOT - c5223721
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package org.graalvm.collections in both module org.graalvm.sdk and module org.graalvm.collections

Had read that is internal's sdk mistake. As provided solution in hope, changed the name of both modules like "org.collections.graalvm" & "org.sdk.graalvm". But, the prove is null, it still not works!
What could it be?

### To Reproduce

Since I have verry addiction about this core, to make a simple playable online 3D world - it happens in storing the Run-package, wherever was placed. Then, with newest java dk, this little (1,338kb) jar, I've got exprienced this error much more.
Used portions of official PNX's Docs.

### Expected behavior

Wanted to... just using command line as default input in server

### Version

c522372

**Comment by CoolLoong** [comment]
Use graalvm21 and https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/8895016055

**Comment by RomaGly55Creations** [comment]
Want more?
![nggyu](https://github.com/PowerNukkitX/PowerNukkitX/assets/86565844/471d02fa-f5bd-4122-ade1-e8930c17793d)

**Comment by guneyilmaz0** [comment]
Delete this file in libs directory
![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/63880117/43c6a081-3ac7-4a10-956b-fecb742cd34d)

**Comment by CoolLoong** [comment]
fixed now https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/8936505183

**Comment by CoolLoong** [comment]
not need to delete lib

**Comment by RomaGly55Creations** [comment]
Thank you!
