### ISSUE TITLE
[Feature]: Find Documentation developer

### ISSUE THREAD

**Issue by CoolLoong** [PowerNukkitX/PowerNukkitX#1581]
![Static Badge](https://img.shields.io/badge/Funded-10$-green?labelColor=yellow)![Static Badge](https://img.shields.io/badge/Through%20PayPal%20-blue)
A developers is needed who can read code and is willing to write documentation, and you will receive patreon funding and help from the other developers.
you need to actively update documentation with PNX updates and write use usage cases for various PNX API.

https://github.com/PowerNukkitX/PNX-Wiki

If interested, contact me on [Discord](https://discord.com/invite/XXus4FB6qf)

**Comment by AzaleeX** [comment]
https://github.com/AzaleeX/PNX-Wiki
