### ISSUE TITLE
[Bug]: Use BDS 1.20.15 World missing block

### ISSUE THREAD

**Issue by yuexps** [PowerNukkitX/PowerNukkitX#1589]
### Describe the bug

world version：BDS 1.20.15
_//地图版本：BDS 1.20.15_

PowerNukkitX version：action commit 509b56a
_//PowerNukkitX版本：action commit 509b56a_

error：missing block hash:-119689719
_//错误：missing block hash:-119689719_

I get an error when putting the BDS Server's World into the PowerNukkitX 2.0 runtime
_//我在将BDS服务器的地图放入PowerNukkitX2.0运行时出现了错误_

### To Reproduce

Put the BDS 1.20.15 server's world into PowerNukkitX 2.0 to run
_//将BDS 1.20.15服务器地的图放入PowerNukkitX2.0运行_

### Expected behavior

no error

### Screenshots

![efdc8ea959ab8d68082ab15ff0120b08](https://github.com/PowerNukkitX/PowerNukkitX/assets/69074603/2abfe66d-fae1-4ca3-9d7f-b1f1a75c85cd)
![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/69074603/71de92e7-2156-48c4-95ef-871ec9c5c4f4)

### Version

action commit 509b56a

**Comment by CoolLoong** [comment]
Share your level

**Comment by yuexps** [comment]
> Share your level

OK，but the level is a large file, I use 123pan to share the level.
https://www.123pan.com/s/e3w7Vv-TZc7v.html
If you are not convenient to use, I can change it to Google Cloud Drive.

**Comment by CoolLoong** [comment]
please use google cloud drive

**Comment by yuexps** [comment]
> please use google cloud drive

This problem may be caused by the use of addon in the level, do you want to continue to fix it?
Uploading to Google Cloud Drive......

**Comment by yuexps** [comment]
> > please use google cloud drive
> 
> This problem may be caused by the use of addon in the level, do you want to continue to fix it? Uploading to Google Cloud Drive......

but the error is still reported after removing Addon

**Comment by yuexps** [comment]
> please use google cloud drive

This level version is 1.20.15
https://drive.google.com/file/d/1M28TVUCflqbMRH3ctbrow51X9WVPWlxE/view?usp=drive_link

**Comment by CoolLoong** [comment]
> he error is still reported after removing Add

Oh, and since there are still blocks in the level from addon, I can add an config to turn off it if you don't think the error is pretty enough

**Comment by yuexps** [comment]
> > he error is still reported after removing Add
> 
> Oh, and since there are still blocks in the level from addon, I can add an config to turn off it if you don't think the error is pretty enough

Okay, and after moving some distance into the server, you get the error shown below
![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/69074603/b49a1f0d-bde4-45ff-a4ea-5c57d825ae71)
