### ISSUE TITLE
PNX organization member request 

### ISSUE THREAD

**Issue by KoshakMineDEV** [PowerNukkitX/PowerNukkitX#1615]
The reason why I'm requesting access to PNX organization is because CoolLoong left the project. Previously I contributed to PNX many times and CoolLoong told me how to update PNX to newer Minecraft versions.

**Comment by OffenLord** [comment]
LGTM
Удачи, бро :)

**Comment by MaXFeeD** [comment]
powerful guy which did depth meter for inner core 🗿👏

**Comment by KoshakMineDEV** [comment]
> powerful guy which did depth meter for inner core 🗿👏

XD
