### ISSUE TITLE
导入图片文件的地图物品，在玩家重新进入时物品异常

### ISSUE THREAD

**Issue by givegrandpaclimb** [PowerNukkitX/PowerNukkitX#162]
![WV%$5 6M14S83YAG%I(UHBH](https://user-images.githubusercontent.com/78897586/158809340-c44145e9-7cc4-41b2-97ed-f63d2907277c.jpg)
操作步骤
1. 通过BN导入图片至地图物品
2. 添加物品到玩家背包
3. 玩家手持该物品（此时地图正常显示图片）
4. 重新进入服务器
5. 地图图片变为黑色和绿色的异常图片（不同时间段异常状况不同）

**Comment by CoolLoong** [comment]
替代品插件https://github.com/PowerNukkitX/ImageNK
