### ISSUE TITLE
Durability of items is poorly synchronized with the customer

### ISSUE THREAD

**Issue by AzaleeX** [PowerNukkitX/PowerNukkitX#1657]
## Description:
When using the latest version of PowerNukkitX, there is a visual bug related to the durability of diamond pickaxes. Breaking a block with a diamond pickaxe and then right-clicking with the item causes the durability to appear as if the item is new. However, the server still tracks the durability correctly.

## Steps to Reproduce:

1. Download and install the latest version of PowerNukkitX.
2. Break a block using a diamond pickaxe.
3. Right-click with the diamond pickaxe.
## Expected Behavior:
The durability of the diamond pickaxe should be displayed correctly after breaking a block and right-clicking.

## Actual Behavior:
The tools appears to have full durability visually, even though the server maintains the correct durability internally.

# Screenshots/Logs:
![image](https://github.com/user-attachments/assets/d4191e97-c893-4bac-a52b-eae6b4971024)

**Comment by Buddelbubi** [comment]
Fixed. Please close
