### ISSUE TITLE
[Bug]: Character creator skin getting rejected as invalid

### ISSUE THREAD

**Issue by maxmwotan** [PowerNukkitX/PowerNukkitX#1665]
### Describe the bug

I can't connect with my character creator skin when the part "tangled_lights" is equipped

### To Reproduce

Equip "tangled_lights" at "persona_outerwear"

### Expected behavior

No error

### Screenshots

![lights](https://github.com/user-attachments/assets/1c4990da-0adf-4c70-a6fb-ab5b447687da)
![errormessage](https://github.com/user-attachments/assets/b9534554-004f-4358-90d8-adba0fd76d00)

### Version

5f8cac2

**Comment by AzaleeX** [comment]
I'm looking at this tomorrow but I was already working on it because I tried too but the server didn't like it, thank you for this bug report

**Comment by AzaleeX** [comment]
I can't get this famous tangled_lights in minecraft but after several tries I can't reproduce your bug even with geometry custom.

**Comment by maxmwotan** [comment]
This here is unfortunately the only error it throws:
![error](https://github.com/user-attachments/assets/5258a306-3ad6-4a76-9ef6-43177bd91e6e)

**Comment by maxmwotan** [comment]
I have found the issue! :D
at `cn.nukkit.entity.data.Skin` the function `isValidSkin` assumes this:
![found](https://github.com/user-attachments/assets/74f49939-734a-487f-acf2-6328435ea20c)

however analysing the debug messages I found out that the skin is actually 32 * 32 meaning the assumption in the the `Skin` class is wrong
![output_data](https://github.com/user-attachments/assets/d2c987b9-168f-4a49-98cb-475d5ba653b8)

**Comment by maxmwotan** [comment]
@AzaleeX I have created a pull request that fixes the issue.
I have already tested my changes in a build :)

**Comment by AzaleeX** [comment]
Thank you for your contribution ❤️
