### ISSUE TITLE
[Bug]: Chorus fruit destination coords are wrong

### ISSUE THREAD

**Issue by maxmwotan** [PowerNukkitX/PowerNukkitX#1666]
### Describe the bug

Chorus fruit destination Y-Coord is a bit too low, therefore the players who use it will sink into the block below.

### To Reproduce

Eat a chorus fruit.

### Expected behavior

Not sink into the floor.

### Screenshots

![chorus](https://github.com/user-attachments/assets/00b54e61-0058-4d65-b2c9-9548c97be7e3)

### Version

5f8cac2

**Comment by AzaleeX** [comment]
I'll take care of it tomorrow, thank you very much for your report on this bug, thank you

**Comment by AzaleeX** [comment]
fix in the next commit on master, thanks again to you ❤️
commit ref: 609c767
pull request: https://github.com/PowerNukkitX/PowerNukkitX/pull/1667
