### ISSUE TITLE
[Todo]: Command Creation Rework

### ISSUE THREAD

**Issue by AzaleeX** [PowerNukkitX/PowerNukkitX#1668]
# Command Creation Rework

**Problem**: The current command creation system is complex, unintuitive, and requires an in-depth understanding of the underlying code. This results in a steep learning curve for new developers and complicates the maintenance and extension of features.

**Objective**: Simplify and standardize the command creation process by drawing inspiration from LiteCommands, a library that offers a more intuitive and structured approach to command management.

## Tasks

1. **Analyze LiteCommands**
   - Study the functionality of LiteCommands.
   - Identify key concepts and structures that can be integrated into our system.

2. **Design the New Command Architecture**
   - Define a new command architecture based on LiteCommands concepts.
   - Create a UML diagram to visualize the interactions between different classes and modules.

3. **Implementation**
   - Develop new classes and methods for command creation.
   - Ensure backward compatibility with existing commands.
   - Write unit tests to validate the new architecture's functionality.

4. **Documentation**
   - Write detailed documentation on the new command creation method.
   - Include practical examples and common use cases.

5. **Migration**
   - Plan and execute the migration of existing commands to the new architecture.
   - Conduct rigorous testing to identify and resolve any issues.

## Acceptance Criteria

- The new architecture should simplify command creation for developers.
- Documentation should be clear and provide concrete examples.
- Unit tests should cover all main use cases.
- No regressions should be introduced in existing commands.

## Resources

- [LiteCommands Documentation](https://litedevelopers.rollczi.dev/)

## Estimated Time

- Analysis and Design: 1 week
- Implementation: 2 weeks
- Documentation: 1 week
- Migration and Testing: 1 week

---

## Example of New Command Creation

Here is a simplified example of how a command might be defined with the new architecture inspired by LiteCommands:

```java
@Command(name = "chat")
@Permission("command.chat")
public class ChatCommand {

    private final ChatManager chatManager = new ChatManager();

    @Execute(name = "on")
    void enableChat(@Context CommandSender sender) {
        this.chatManager.enableChat();
    }

    @Execute(name = "off")
    void disableChat(@Context CommandSender sender) {
        this.chatManager.disableChat();
    }

    @Execute(name = "clear")
    @Permission("command.chat.clear")
    void clearChat(@Context CommandSender sender, @Arg int lines) {
        this.chatManager.clearChat(lines);
    }

}
```

**Comment by smartcmd** [comment]
😅

**Comment by AzaleeX** [comment]
> 😅

????

**Comment by smartcmd** [comment]
In fact we have considered LiteCommand, CloudCommand and Brigadier when we are writing commands 2 years ago

**Comment by AzaleeX** [comment]
> In fact we have considered LiteCommand, CloudCommand and Brigadier when we are writing commands 2 years ago

ah, but LiteCommand schemas are spotless

**Comment by smartcmd** [comment]
> > In fact we have considered LiteCommand, CloudCommand and Brigadier when we are writing commands 2 years ago
> 
> ah, but LiteCommand schemas are spotless

When you get deeper, you'll find that all the 3rd command frameworks are not suitable for pnx (for bedrock)

**Comment by maxmwotan** [comment]
In Java 8 there's this way of writing this, which should be faster while keeping the code easier to read and understand.
Maybe you'd like to take inspiration from it?

**Inside the plugin class** : write a function, pass it in as this::func
```java
public class MyPlugin
{
  public MyPlugin()
  {
    cmdMgr.addCmd(this::gmCmd, "gamemode", "gm");
  }

  /** def of λ-cmd */
  public void gmCmd(String args[])
  {
    // sets gamemode by args[0]
    // optionally Player from args[1]
  }
}
```

**Type representing the λ-function - almost the same as a Consumer**
```java
public interface Command
{
  public void call(String[] args);
}
```

**Here the implementation code** : for indexing and filtering commands for calling them with `λ.call(args)`
```java
public class CmdMgr
{
  public void addCmd(Command λ, String... name)
  {
    cmdList.add(λ, name);
  }
}
```
