### ISSUE TITLE
[Feature]: Enable Village Generation

### ISSUE THREAD

**Issue by eat-sleep-code** [PowerNukkitX/PowerNukkitX#1705]
### Is your feature request related to a problem? Please describe.

The latest version of PowerNukkitX does not appear to have village generation enabled.   

While I have seen Mobs (Creepers, Zombies, Horses, Sheep, Bees, Spiders, etc.) be generated I have not seen an auto generation of villages or villagers.   

I am running  2.0.0-SNAPSHOT - 908c1481 and MobPlugin v1.26.3-PNX

### Describe the solution you'd like

Enable automatic random village generation.

### Describe alternatives you've considered

Being sad that there isn't villages auto generated? 😄

**Comment by KoshakMineDEV** [comment]
There will be not Village generation. The only one 100% supported officialy world generator is just FLAT without anything. Mobs are generated by MobPlugin, not PNX. There's no villages in flat world in bedrock, so same thing on PNX

**Comment by eat-sleep-code** [comment]
I am using Terra.   Would villages generated by Terra or MobPlugin?   I have MobPlugin but not seeing any villages.

**Comment by Buddelbubi** [comment]
You'd have to change the code of mob plugin to generate those in the terra generator

**Comment by eat-sleep-code** [comment]
Is MobPlugin even maintained anymore?

**Comment by Buddelbubi** [comment]
> Is MobPlugin even maintained anymore?

Not by us. The PNX dev team shrunk too much. We can not maintain all the plugins. Feel free to maintain it with pr's. Your help would be appreciated.
