### ISSUE TITLE
[Bug]: why random tick not working ?

### ISSUE THREAD

**Issue by angga7togk** [PowerNukkitX/PowerNukkitX#1715]
### Describe the bug

i generate world, in custom generator empty, i want create a oneblock game, but i try plant the spaling, i waited a long time nothing happened

### To Reproduce

i generate world, in custom generator empty, i want create a oneblock game, but i try plant the spaling, i waited a long time nothing happened

### Expected behavior

fix it

### Screenshots

![image](https://github.com/user-attachments/assets/1e3714dc-d3d7-4170-929b-94bc91b0ebfe)
![image](https://github.com/user-attachments/assets/9292b202-77d8-4d0e-a2b9-5a1d89b3921e)

### Version

1.21.30

**Comment by Buddelbubi** [comment]
Place a light source nearby or calculate the lights with a plugin
