### ISSUE TITLE
[Bug]: An error occurred while unzipping the powernukkitx-run.zip

### ISSUE THREAD

**Issue by IPlayForPlayer** [PowerNukkitX/PowerNukkitX#1716]
### Describe the bug

There was an error in the fastutil-8.5.12.jar in the powernukkitx-run.zip provided by the github page, which directly caused the folder to fail to unzip. If you skip the file, you will not be able to start the server because the file is missing:

21:53:37 [INFO ] Using JVM: Java HotSpot(TM) 64-Bit Server VM1
21:53:37 [INFO ] Using PNX core: 2.0.0-SNAPSHOT - cbeacd21
Java HotSpot(TM) 64-Bit Server VM warning: Option ZGenerational was deprecated in version 23.0 and will likely be removed in a future release.
21:53:38 [main] [INFO] Loading nukkit.yml...
21:53:38 [main] [INFO] Loading server.properties...
21:53:38 [main] [INFO] Selected English (eng) as the base language
21:53:38 [main] [INFO] Starting Minecraft: BE server version v1.21.40
21:53:38 [main] [INFO] Selected Zlib provider: 3 (cn.nukkit.compression.LibDeflateThreadLocal)
21:53:38 [main] [INFO] This server is running PowerNukkitX version 2.0.0-SNAPSHOT (git-cbeacd2) (API 2.0.0)
21:53:38 [main] [INFO] PowerNukkitX is distributed under the LGPL License
21:53:38 [main] [ERROR]
java.lang.NoSuchMethodError: 'java.lang.Object it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.putIfAbsent(int, java.lang.Object)'
        at cn.nukkit.registry.PacketRegistry.register0(PacketRegistry.java:78) ~[powernukkitx.jar:?]
        at cn.nukkit.registry.PacketRegistry.registerPackets(PacketRegistry.java:88) ~[powernukkitx.jar:?]
        at cn.nukkit.registry.PacketRegistry.init(PacketRegistry.java:18) ~[powernukkitx.jar:?]
        at cn.nukkit.Server.<init>(Server.java:418) ~[powernukkitx.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:159) [powernukkitx.jar:?]
21:53:38 [main] [INFO] Stopping other threads

### To Reproduce

unzipped powernukkitx-run.zip

### Expected behavior

can‘t unzip the powernukkitx-run.zip
or
not be able to start server

### Screenshots

![image](https://github.com/user-attachments/assets/b52d2528-9062-45c5-969e-3f14bff65737)
![image](https://github.com/user-attachments/assets/0afd2017-f00c-43e2-9e2e-8b75f1954f2c)

**Comment by AzaleeX** [comment]
I have never had this problem, I think it doesn't happen often

**Comment by Buddelbubi** [comment]
Cannot reproduce. Try a different unzipper.
Default Windows 11 and winrar have no problems unzipping that file.
