### ISSUE TITLE
天光计算错误

### ISSUE THREAD

**Issue by Superice666** [PowerNukkitX/PowerNukkitX#201]
# 🐞 错误汇报

区块的天光在384区块更新后无法正确计算

### ✔ 预期行为

https://wiki.biligame.com/mc/%E4%BA%AE%E5%BA%A6

### ❌ 实际行为

#160

**Comment by Mcayear** [comment]
/time set night
时 阳光传感器应该激活2格信号，并且在10秒后衰落为1格信号。

**Comment by Mcayear** [comment]
/time set midnight
时 阳光传感器不激发信号
