### ISSUE TITLE
卸載區怪錯誤

### ISSUE THREAD

**Issue by Ootmnt150oO** [PowerNukkitX/PowerNukkitX#227]
# 🐞 错误汇报

![image](https://user-images.githubusercontent.com/60053027/163668866-a4e18343-279a-4f66-9772-edcc28dd77aa.png)

### 📸 截图或视频

![image](https://user-images.githubusercontent.com/60053027/163668858-240016f7-0602-4540-a582-85734b11ed6b.png)

**Comment by Superice666** [comment]
@smartcmd 貌似经过核查，是你的计分板修改导致的

**Comment by lt-name** [comment]
已被修复
