### ISSUE TITLE
岩浆和虚空伤害没有间隔

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#238]
# 🐞 错误汇报

- 岩浆和虚空的伤害没有间隔。

# 版本
[https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/2179062715](https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/2179062715)

**Comment by smartcmd** [comment]
修了一个
