### ISSUE TITLE
玩家进入游戏自动关服

### ISSUE THREAD

**Issue by Elaina1314** [PowerNukkitX/PowerNukkitX#274]
# 🐞 错误汇报

以下是部分日志，太多了，可能会漏下一点
![Screenshot_2022-05-01-11-46-16-711_com termux jpg](https://user-images.githubusercontent.com/100994314/166131459-a92fddc5-0ffb-4a1e-abde-516d6b6078a0.png)
![Screenshot_2022-05-01-11-46-19-566_com termux jpg](https://user-images.githubusercontent.com/100994314/166131460-75f7c074-b802-42f4-ae8b-ed14f42303a7.png)
![Screenshot_2022-05-01-11-43-14-595_com termux jpg](https://user-images.githubusercontent.com/100994314/166131462-358e13a9-f07d-4fa7-b26d-5d6128909440.png)
![Screenshot_2022-05-01-11-45-36-672_com termux jpg](https://user-images.githubusercontent.com/100994314/166131466-37684ae3-2eed-4099-b130-6538d34bb7af.png)
![Screenshot_2022-05-01-11-45-41-993_com termux jpg](https://user-images.githubusercontent.com/100994314/166131468-986d84a9-e73c-47d4-a4b2-581610a10299.png)
![Screenshot_2022-05-01-11-45-46-290_com termux jpg](https://user-images.githubusercontent.com/100994314/166131471-2991ead8-f260-4110-a366-7779ca12a7a3.png)
![Screenshot_2022-05-01-11-45-50-583_com termux jpg](https://user-images.githubusercontent.com/100994314/166131474-cd6e963e-8545-43ca-91f3-1b3cfdc86ef9.png)
![Screenshot_2022-05-01-11-45-54-699_com termux jpg](https://user-images.githubusercontent.com/100994314/166131476-bb949f06-a1cd-4e11-87de-8b9aaa239c75.png)
![Screenshot_2022-05-01-11-46-00-386_com termux jpg](https://user-images.githubusercontent.com/100994314/166131478-a690dfb7-c735-4937-b938-11fdd4c670fa.png)
![Screenshot_2022-05-01-11-46-06-555_com termux jpg](https://user-images.githubusercontent.com/100994314/166131480-d868d6ca-b958-44f7-9d1a-b40b41866640.png)

![Screenshot_2022-05-01-11-46-10-971_com termux jpg](https://user-images.githubusercontent.com/100994314/166131454-cc9c134a-0557-426b-922a-f71cf0d60726.png)
![Screenshot_2022-05-01-11-46-14-231_com termux jpg](https://user-images.githubusercontent.com/100994314/166131457-e380bc8e-7ae4-4027-b463-37a1b876ea74.png)

**Comment by lt-name** [comment]
日记较多的情况下可以直接发日记文件

**Comment by Elaina1314** [comment]
> 日记较多的情况下可以直接发日记文件
好的 我编辑一下

**Comment by Superice666** [comment]
BlocklyNukkit版本太老，请换用r13版本
