### ISSUE TITLE
新实现初步运动时怪物在水草上无法上浮

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#293]
# 🐞 错误汇报
怪物蛋在水草上无法正常上浮

### 📸 截图或视频

![X O`F6}Y4Y6~G837B8X@(MG](https://user-images.githubusercontent.com/61540722/166953774-78679641-643b-4ac4-8d68-9f486f0f50bf.png)

### ▶ 复现步骤

在水下使用怪物蛋在高速生成下触发
### ✔ 预期行为

会上浮

### ❌ 实际行为

不会上浮

**Comment by Superice666** [comment]
能发送进一步信息吗，目前暂时无法复现
