### ISSUE TITLE
pnx无法跑满核心

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#294]
# 🐞 错误汇报
在12代酷睿 12700F中 生成大约4000实体但是只有其中1个核心在打架其它核心在围观

### 📸 截图或视频

![VE958{J98 064IK5}$%FHUL](https://user-images.githubusercontent.com/61540722/166959536-0b650e8d-3a34-4fb4-a358-9894b8436c37.png)

### ▶ 复现步骤
使用命令方块生成 4000+牛

### ✔ 预期行为
全核集火

### ❌ 实际行为
单核打架多核围观

**Comment by lt-name** [comment]
现在大部分实体计算都是在主线程进行的

**Comment by CivicXFB** [comment]
那没事了，但是如果占用主线程的话为啥我吃东西和挖掘都非常流畅

**Comment by Superice666** [comment]
已经完成初步优化

**Comment by Superice666** [comment]
实体AI优化基本完成，后续将针对各个场景进行针对性优化，感谢支持
