### ISSUE TITLE
自然生成的地狱中无法通过铁桶收集岩浆

### ISSUE THREAD

**Issue by Pigeon2333** [PowerNukkitX/PowerNukkitX#306]
# 🐞 错误汇报

### 📸 截图或视频
![`A@TEMZT%E$7%`~G57S9IJ4](https://user-images.githubusercontent.com/68182691/167277808-fff1c499-a8ee-45d2-a1f8-d289ba34beac.jpg)

### ▶ 复现步骤
1.使用Nukkit 1.6.0.0-PNX-SNAPSHOT (git-7a5b0d3)运行一个新的服务端，并在配置中允许地狱的生成
2.确认地狱是自然生成的，而不是此前预先设置的地图
3.生存模式下进入地狱，使用空铁桶尝试收集岩浆

### ✔ 预期行为
岩浆应当被空桶收集

### ❌ 实际行为
岩浆似乎就像空气方块一样无法被空桶收集

### 📋 Debug information
无

### 💢 错误堆栈或崩溃日志
无

### 💬 其他信息
PNX版本：Nukkit 1.6.0.0-PNX-SNAPSHOT (git-7a5b0d3)

**Comment by lt-name** [comment]
无法复现，请提供更多信息

**Comment by Pigeon2333** [comment]
> 无法复现，请提供更多信息

要不你来FAP空岛生存的地狱亲自体验一下。。。。

**Comment by lt-name** [comment]
可能是https://github.com/PowerNukkitX/PowerNukkitX/issues/259 影响
请先更新pnx到最新版本
