### ISSUE TITLE
FAWE No Biomes cannot //setbiome and //biomelist.

### ISSUE THREAD

**Issue by LemonCraft-11** [PowerNukkitX/PowerNukkitX#311]
# 🔌 Plugin compatibility issue

FAWE When I type the command /biomelist , Biome is displayed.
and said that there is only 1/1

### 📸 Screenshots / Videos

![image](https://user-images.githubusercontent.com/74866868/167765522-49ba2eba-7644-4f9f-a66f-30d88ea0865b.png)

### ▶ Steps to Reproduce

1. Run command '//setbiome'
2. Run command '//biomelist'
3. Don't have Biomes

### ✔ Expected Behavior

Fix the command //setbiomes //biomelist

### 📋 Debug information

* PowerNukkitX version: ✍1.6.0.0-PNX-SNAPSHOT (git-275f855)
* Debug link: ✍
* Timings link (if relevant): ✍ 

### 💬 Anything else we should know?

 Pls fix command //setbiome and //biomelist

**Comment by feanchy** [comment]
my faw doesn't load at all :/

**Comment by LemonCraft-11** [comment]
Thank you
