### ISSUE TITLE
Plotsquared PowernukkitX 

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#315]
# 🔌 Plugin compatibility issue
 [36m11:02:30[m [[m[34mINFO [m[m] Enabling PlotSquared v19.12.10-b4c257b-783

Version is PlotSquared-19.12.10-b4c257b-4

java.lang.NoSuchFieldException: modifiers

at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

at com.intellectualcrafters.plot.config.Config.setAccessible(Config.java:356)

at com.intellectualcrafters.plot.config.Config.save(Config.java:207)

at com.intellectualcrafters.plot.config.Config.save(Config.java:110)

at com.intellectualcrafters.plot.config.Settings.save(Settings.java:42)

at com.intellectualcrafters.plot.PS.setupConfig(PS.java:1687)

at com.intellectualcrafters.plot.PS.setupConfigs(PS.java:1717)

at com.intellectualcrafters.plot.PS.<init>(PS.java:149)

at com.plotsquared.nukkit.NukkitMain.onEnable(NukkitMain.java:80)

at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:105)

at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)

at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:463)

at cn.nukkit.Server.enablePlugin(Server.java:996)

at cn.nukkit.Server.enablePlugins(Server.java:985)

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkitX version: (git-d512ab7)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
Another Plotsquared MySQL Problem

Failed to set config option: issues: https://github.com/IntellectualSites/PlotSquared/issues | com.intellectualcrafters.plot.config.Settings@5868ea91
2022-05-14 10:30:45.934 [main] INFO  - Invalid config field: suggestion for settings
2022-05-14 10:30:45.935 [main] INFO  - Failed to set config option: suggestion: https://github.com/IntellectualSites/PlotSquaredSuggestions | com.intellectualcrafters.plot.config.Settings@757c685d
2022-05-14 10:30:45.935 [main] INFO  - Invalid config field: wiki for settings
2022-05-14 10:30:45.936 [main] INFO  - Failed to set config option: wiki: https://github.com/IntellectualSites/PlotSquared/wiki | com.intellectualcrafters.plot.config.Settings@476a970c
2022-05-14 10:30:45.936 [main] INFO  - Invalid config field: date for settings
2022-05-14 10:30:45.936 [main] INFO  - Failed to set config option: date: 9 Jan 2020 23:00:00 GMT | com.intellectualcrafters.plot.config.Settings@1ce57bbb
2022-05-14 10:30:45.937 [main] INFO  - Invalid config field: build for settings
2022-05-14 10:30:45.937 [main] INFO  - Failed to set config option: build: https://ci.athion.net/job/PlotSquared/4 | com.intellectualcrafters.plot.config.Settings@34626d4
2022-05-14 10:30:45.937 [main] INFO  - Invalid config field: commit for settings
2022-05-14 10:30:45.938 [main] INFO  - Failed to set config option: commit:

**Comment by MonoAdrian23** [comment]
Failed to set config option: uuid.force-lowercase: false | com.intellectualcrafters.plot.config.Settings$UUID@40277077

[36m14:43:00[m [[m[34mINFO [m[m] Invalid config field: uuid.use-sqluuidhandler for uuid

[36m14:43:00[m [[m[34mINFO [m[m] Failed to set config option: uuid.use-sqluuidhandler: false | com.intellectualcrafters.plot.config.Settings$UUID@4cb773c5

[36m14:43:00[m [[m[34mINFO [m[m] Invalid config field: chunk-processor.auto-trim for chunk-processor

[36m14:43:00[m [[m[34mINFO [m[m] Failed to set config option: chunk-processor.auto-trim: false | com.intellectualcrafters.plot.config.Settings$Chunk_Processor@3f33bb6f

[36m14:43:00[m [[m[34mINFO [m[m] Invalid config field: chunk-processor.max-tiles for chunk-processor

[36m14:43:00[m [[m[34mINFO [m[m] Failed to set config option: chunk-processor.max-tiles: 4096 | com.intellectualcrafters.plot.config.Settings$Chunk_Processor@446cc036

[36m14:43:00[m [[m[34mINFO [m[m] Invalid config field: chunk-processor.max-entities for chunk-processor

**Comment by CoolLoong** [comment]
> Another Plotsquared MySQL Problem
> 
> Failed to set config option: issues: https://github.com/IntellectualSites/PlotSquared/issues | com.intellectualcrafters.plot.config.Settings@5868ea91 2022-05-14 10:30:45.934 [main] INFO - Invalid config field: suggestion for settings 2022-05-14 10:30:45.935 [main] INFO - Failed to set config option: suggestion: https://github.com/IntellectualSites/PlotSquaredSuggestions | com.intellectualcrafters.plot.config.Settings@757c685d 2022-05-14 10:30:45.935 [main] INFO - Invalid config field: wiki for settings 2022-05-14 10:30:45.936 [main] INFO - Failed to set config option: wiki: https://github.com/IntellectualSites/PlotSquared/wiki | com.intellectualcrafters.plot.config.Settings@476a970c 2022-05-14 10:30:45.936 [main] INFO - Invalid config field: date for settings 2022-05-14 10:30:45.936 [main] INFO - Failed to set config option: date: 9 Jan 2020 23:00:00 GMT | com.intellectualcrafters.plot.config.Settings@1ce57bbb 2022-05-14 10:30:45.937 [main] INFO - Invalid config field: build for settings 2022-05-14 10:30:45.937 [main] INFO - Failed to set config option: build: https://ci.athion.net/job/PlotSquared/4 | com.intellectualcrafters.plot.config.Settings@34626d4 2022-05-14 10:30:45.937 [main] INFO - Invalid config field: commit for settings 2022-05-14 10:30:45.938 [main] INFO - Failed to set config option: commit:

I use Mysql without warning
![%L($_VADLT26I8)ARRD0W9D](https://user-images.githubusercontent.com/69153398/169702303-c787d028-e60f-4239-81bc-c0ab46dd47af.png)

**Comment by CoolLoong** [comment]
> # 🔌 Plugin compatibility issue
> [36m11:02:30[m [[m[34mINFO [m[m] Enabling PlotSquared v19.12.10-b4c257b-783
> Version is PlotSquared-19.12.10-b4c257b-4
> 
> java.lang.NoSuchFieldException: modifiers
> 
> at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
> 
> at com.intellectualcrafters.plot.config.Config.setAccessible(Config.java:356)
> 
> at com.intellectualcrafters.plot.config.Config.save(Config.java:207)
> 
> at com.intellectualcrafters.plot.config.Config.save(Config.java:110)
> 
> at com.intellectualcrafters.plot.config.Settings.save(Settings.java:42)
> 
> at com.intellectualcrafters.plot.PS.setupConfig(PS.java:1687)
> 
> at com.intellectualcrafters.plot.PS.setupConfigs(PS.java:1717)
> 
> at com.intellectualcrafters.plot.PS.(PS.java:149)
> 
> at com.plotsquared.nukkit.NukkitMain.onEnable(NukkitMain.java:80)
> 
> at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:105)
> 
> at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)
> 
> at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:463)
> 
> at cn.nukkit.Server.enablePlugin(Server.java:996)
> 
> at cn.nukkit.Server.enablePlugins(Server.java:985)
> 
> ### 📸 Screenshots / Videos
> ### ▶ Steps to Reproduce
> 1. Run command '...'
> 2. Click on '....'
> 3. Put '....' at '...'
> 4. See error
> 
> ### ✔ Expected Behavior
> ### ❌ Actual Behavior
> ### 📋 Debug information
> * PowerNukkitX version: (git-d512ab7)
> * Debug link: ✍
> * Timings link (if relevant): ✍
> 
> ### 💢 Crash Dump, Stack Trace and Other Files
> ### 💬 Anything else we should know?

The console error does not affect the plugin function.
We'll solve it later.

**Comment by CoolLoong** [comment]
> Another Plotsquared MySQL Problem
> 
> Failed to set config option: issues: https://github.com/IntellectualSites/PlotSquared/issues | com.intellectualcrafters.plot.config.Settings@5868ea91 2022-05-14 10:30:45.934 [main] INFO - Invalid config field: suggestion for settings 2022-05-14 10:30:45.935 [main] INFO - Failed to set config option: suggestion: https://github.com/IntellectualSites/PlotSquaredSuggestions | com.intellectualcrafters.plot.config.Settings@757c685d 2022-05-14 10:30:45.935 [main] INFO - Invalid config field: wiki for settings 2022-05-14 10:30:45.936 [main] INFO - Failed to set config option: wiki: https://github.com/IntellectualSites/PlotSquared/wiki | com.intellectualcrafters.plot.config.Settings@476a970c 2022-05-14 10:30:45.936 [main] INFO - Invalid config field: date for settings 2022-05-14 10:30:45.936 [main] INFO - Failed to set config option: date: 9 Jan 2020 23:00:00 GMT | com.intellectualcrafters.plot.config.Settings@1ce57bbb 2022-05-14 10:30:45.937 [main] INFO - Invalid config field: build for settings 2022-05-14 10:30:45.937 [main] INFO - Failed to set config option: build: https://ci.athion.net/job/PlotSquared/4 | com.intellectualcrafters.plot.config.Settings@34626d4 2022-05-14 10:30:45.937 [main] INFO - Invalid config field: commit for settings 2022-05-14 10:30:45.938 [main] INFO - Failed to set config option: commit:

I think you should check your config

**Comment by MonoAdrian23** [comment]
Its the Default config

**Comment by MonoAdrian23** [comment]
And it works with Nukkit and Powernukkit
It must be a PNX Problem

**Comment by CoolLoong** [comment]
This error message indicates that your config file is set incorrectly

**Comment by MonoAdrian23** [comment]
But i have changed nothing.
I think my Version is generating a Plot world by itself without /p setup.
Because only this world is free of Bugs.
Hm

**Comment by CoolLoong** [comment]
I use /plot setup,everthing prefect.
I don't understand what you say "generating a Plot world by itself",you changed nukkit.yml?

**Comment by MonoAdrian23** [comment]
I use a Custom Version of Plotsquared

This Plugin generate a Plotworld without Bugs.

Plotsquared from Cloudburst have Many Bugs.

Can i contact you at Discord?

**Comment by CoolLoong** [comment]
sure
