### ISSUE TITLE
Nether Spawn is above Bedrock

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#316]
# 🐞 错误汇报
 Use Multiworld Plugin and Type /mw tp nether.
You Spawn at Bedrock Border.

**Comment by lt-name** [comment]
在 https://github.com/PowerNukkitX/PowerNukkitX/commit/d363ed8bc19b3955c2be321ccbd0e207f27a5aab 修复
