### ISSUE TITLE
部分情况下玩家背包内物品无法移动，丢弃，使用

### ISSUE THREAD

**Issue by 3zeroed** [PowerNukkitX/PowerNukkitX#318]
# 🐞 错误汇报
部分情况下玩家背包内物品无法移动，丢弃，使用

### 📸 截图或视频
视频在群里，下图为复现这种情况的代码
![image](https://user-images.githubusercontent.com/44516212/168255851-89298275-5e65-4dfb-acb3-381df180d086.png)

### ▶ 复现步骤
目前已知在玩家死亡后清除背包内容，然后重生时再给予背包内容，就会出现这种情况

### 💢 错误堆栈或崩溃日志
没有错误日志

**Comment by 3zeroed** [comment]
今天又测试了一下，在不装插件的情况下，开启死亡不掉落/gamerule keepinventory true，就会出现这种情况

**Comment by 3zeroed** [comment]
刚才又测试了下，只要给物品随便写入点tag就不会触发这个bug
![image](https://user-images.githubusercontent.com/44516212/168408719-4467168b-d41f-4f3d-945f-ca1d272b5c77.png)
使用上方代码可以暂时解决这个问题

**Comment by 3zeroed** [comment]
如果你遇到这种情况可暂时使用此插件来解决->https://github.com/3zeroed/ItemExceptionFix

**Comment by lt-name** [comment]
在 https://github.com/PowerNukkitX/PowerNukkitX/commit/6f230d08d5cb800f19345aad47a1da0a4cd48fae https://github.com/PowerNukkitX/PowerNukkitX/commit/224ea7bc4a5257b65d9fa51ae1e901a9b1daceaf 修复
