### ISSUE TITLE
地狱生成地狱门浮空生成

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#32]
# 🐞 错误汇报

在四周都有陆地情况下地狱门浮空生成, 在原版没有这个bug
### 📸 截图或视频

![屏幕截图 2022-02-08 120305](https://user-images.githubusercontent.com/61540722/152916184-d75a1150-2d54-42e3-b787-ba016b3a0668.png)

### ▶ 复现步骤

1 构建地狱传送门
2 进入地狱
3 有一定几率

### ✔ 预期行为

在周围陆地上产生地狱传送门

### ❌ 实际行为

浮空产生地狱传送门

### 📋 Debug information

无
### 💢 错误堆栈或崩溃日志

无

### 💬 其他信息

使用powernukkitx #30构建

**Comment by CivicXFB** [comment]
从地狱返回主世界时 人会出现在地狱门上方

**Comment by CivicXFB** [comment]
64 格高度

**Comment by Ootmnt150oO** [comment]
我怎麼記得是會生成再空中 但是周圍會有一點黑曜石當作路

**Comment by Hanmo123** [comment]
> 我怎麼記得是會生成再空中 但是周圍會有一點黑曜石當作路

在我服务器里生成了3x3的黑曜石踮脚平台，但是类似门在空中生成的情况我只在JE服碰到过
