### ISSUE TITLE
First Release for PowernukkitX

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#320]
# 🤷‍♀️ I have a question

Is there a Date for First Release Version?
Because this Software is great.

### 📋 Debug information

* PowerNukkitX version: ✍
* Debug link: ✍

**Comment by chencu5958** [comment]
Not sure for now, because there are still a lot of undeveloped features waiting to be perfected

**Comment by chencu5958** [comment]
Hello, we have updated the released version of powernukkitx, you can view it here https://github.com/PowerNukkitX/PowerNukkitX/releases
