### ISSUE TITLE
Big Mushrooms doesnt Drop Mushrooms

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#323]
# 🐞 错误汇报
 Big Mushrooms should Drop Mushrooms but it Drops nothing.

**Comment by zimzaza4** [comment]
wait, big mushrooms?

**Comment by MonoAdrian23** [comment]
![Huge_Red_Mushroom.png](https://user-images.githubusercontent.com/59027482/168437463-e797ddc3-179b-49a9-a2b6-08afd8117a51.png)

**Comment by MonoAdrian23** [comment]
https://minecraft.fandom.com/wiki/Huge_mushroom

For all Informations

**Comment by zimzaza4** [comment]
ok, i try to break about 100 big mushrooms in demo server and they drop nothing. :P

**Comment by MonoAdrian23** [comment]
Droprate 

2-25 Mushrooms
With Shears or Sword i think
