### ISSUE TITLE
方块实体回收泄漏

### ISSUE THREAD

**Issue by smartcmd** [PowerNukkitX/PowerNukkitX#331]
![image](https://user-images.githubusercontent.com/60499296/168436901-c8e9a947-84bd-4744-b85b-6b98cf40481d.png)
![image](https://user-images.githubusercontent.com/60499296/168436906-6e2f6d8c-b629-4fd0-af61-51bd392e52b1.png)
/clone和命令方块会导致已破坏方块的方块实体不能被核心正常回收
原因未知

**Comment by Superice666** [comment]
此问题仍然没有得到处理，重新打开

**Comment by smartcmd** [comment]
现在应该好了

**Comment by lt-name** [comment]
在 https://github.com/PowerNukkitX/PowerNukkitX/commit/ac074eaaaf449e71e9c8b1700db4240cfceb2879 修复
