### ISSUE TITLE
Enchantet Books from fishing doenst have any Enchants 

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#342]
# 🐞 错误汇报
 Use a Fishing Hook and Go fish.
Hopefully you get a Enchanted Book, but there is No Enchant available.
Same with all by Wode Structure Plugins Like Temples, Wrecks, etc.

**Comment by MonoAdrian23** [comment]
All

**Comment by MonoAdrian23** [comment]
Same Issue is existing in Powernukkit i see

**Comment by smartcmd** [comment]
重复了
