### ISSUE TITLE
Plugin error with PowerNukkitX

### ISSUE THREAD

**Issue by LemonCraft-11** [PowerNukkitX/PowerNukkitX#348]
# 🔌 Plugin compatibility issue

some plugin is error with PowernukkitX
i'm test with plugin GAC & AuctionHouse

### 📸 Screenshots / Videos

( AuctionHouse )
![image](https://user-images.githubusercontent.com/74866868/169258108-54794a78-db40-4f7e-8388-962c47b3644c.png)

( GAC )
![image](https://user-images.githubusercontent.com/74866868/169258251-0592e5e4-babc-4cdc-afbb-f05700db71c2.png)

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkitX version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
Yes and Fakeinventorys doenst work too

**Comment by MonoAdrian23** [comment]
And Luckperms have this Issue and Not Gac.

**Comment by LemonCraft-11** [comment]
> Yes and Fakeinventorys doenst work too

FakeInventory don't support PowerNukkitX?

**Comment by MonoAdrian23** [comment]
Only the Powernukkit Version works.
The Fakeinventorys ( Nukkit ) Plugin sends a Tons of Errors when using with Plugins Like Invsee, AuctionHouse, Enderchest etc

And AuctionHouse haves a big Money Dupe Bug.
