### ISSUE TITLE
Option for disable Portal Creation

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#353]
# ❇ Feature Request
 Hello PNX Team.
Can you add an Option for disabling Portal Creation in Certain Worlds?
Its Not good for Citybuild Servers and Minigame Servers.

Thank You very much ♥️

**Comment by CoolLoong** [comment]
You can write a plugin to control.

**Comment by MonoAdrian23** [comment]
I have.
I Close this
