### ISSUE TITLE
PowerNukkitX don't have Anti-Cheat

### ISSUE THREAD

**Issue by LemonCraft-11** [PowerNukkitX/PowerNukkitX#356]
# 🔌 Plugin compatibility issue

PowerNukkitX don't have Anti-Cheat
### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkitX version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Superice666** [comment]
Use WatchDogX by @rainbow188

**Comment by Pigeon2333** [comment]
Watchdog is compatible with PNX.Join discord:https://discord.gg/6BVU7jwkux
