### ISSUE TITLE
Sometimes, Player Spawn Random in Caves

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#357]
# 🐞 错误汇报
 Title say all
I have logged Out in Badlands Biom
New Login spawnpoint was in a Random Cave.
This Issue existing in Powernukkit too.

**Comment by Superice666** [comment]
Thanks a lot for your report! Could you please tell us if you restarted your server during the time that you're offline?

**Comment by feanchy** [comment]
same problem
