### ISSUE TITLE
Pets doenst follow in Other Worlds

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#358]
# 🐞 错误汇报
 I have tested with Certain Plugins to add pets.
I can create a pet with LlamaPets for example but the Pet doenst follow in another worlds.
I think there is No pet follow function implemented in Nukkit.

**Comment by Superice666** [comment]
Could you please tell us the version of your pnx using in your server?

**Comment by Blackjack200** [comment]
please ask for LlamaPets developer
