### ISSUE TITLE
Clicking an NPC, remove the NPC and the NPC cant be edit

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#361]
# 🐞 错误汇报
 Title say all
(git-f164985)

**Comment by MonoAdrian23** [comment]
I rejoin the Server and all NPCs are alive xd.
But they dissapear with a Click

**Comment by smartcmd** [comment]
check that you are using the newest server core
I remember this bug has been solved  When I first started writing npc
