### ISSUE TITLE
All available Clearlag Plugins remove NPC

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#362]
# 🔌 Plugin compatibility issue
 All available Clearlag Plugin that remove Mobs, Items, NPcs are compatible but all These Plugins remove the PNX NPCs

For Example: "LlamaButcher" 

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkitX version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Superice666** [comment]
Many plugins including LlamaButcher only checks if an entity is player. We recommend that you contact the authors of these plugins to resolve the issue. Thanks.
