### ISSUE TITLE
末影水晶连续引爆破坏方块时会同时掉落多份方块

### ISSUE THREAD

**Issue by smartcmd** [PowerNukkitX/PowerNukkitX#391]
![image](https://user-images.githubusercontent.com/60499296/173222077-782d2148-0bd6-498f-ac50-194d540e5c3c.png)
![image](https://user-images.githubusercontent.com/60499296/173222081-02e185ef-4ba8-47cf-bafd-7b22ebe2b62f.png)

**Comment by CoolLoong** [comment]
我认为这个bug在生存模式下不可能复现，可以不修复
