### ISSUE TITLE
Library loader java 17

### ISSUE THREAD

**Issue by feanchy** [PowerNukkitX/PowerNukkitX#399]
Expected Behavior
Normal libraries loading

Actual Behavior
Error

Steps to Reproduce
Try using LibraryLoader.load with java 17

Screenshot: (https://user-images.githubusercontent.com/50043944/173685089-2e794f1b-3ff4-4a12-aee9-ff79b5e7ec83.png)

**Comment by Superice666** [comment]
see here:
https://doc.powernukkitx.cn/en-us/faq/Server_faq.html

**Comment by feanchy** [comment]
> см. здесь: https://doc.powernukkitx.cn/en-us/faq/Server_faq.html

I didn't really understand how to do this, for example, I have this download script:
@echo off
java -Xmx2g -Xms2g -jar powernukkit.jar
pause
please send the corrected version
