### ISSUE TITLE
PowerNukkit历史遗留BUG列表（统计中）

### ISSUE THREAD

**Issue by chencu5958** [PowerNukkitX/PowerNukkitX#40]
# 🐞 错误汇报

这些漏洞都为PowerNukkit就存在的漏洞，但影响有大有小
### ▶ 复现步骤

1.[Issue#1325](https://github.com/PowerNukkit/PowerNukkit/issues/1325)（补充：使用工作台合成未签名的书和签名的书，实际应该是合成出两本相同且已签名的书，但合成后只出现一本未签名的书）

### ✔ 已修复的漏洞

目前已修复的PowerNukkit遗留问题清单
1.[Issue#1192](https://github.com/PowerNukkit/PowerNukkit/issues/1192)（补充：该BUG可将栅栏等方块用打火石点燃）（已在[构建版本#145](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1812465166)中修复）
2.[Issue#1251](https://github.com/PowerNukkit/PowerNukkit/issues/1251)（补充：该BUG会小概率导致玩家出生在岩浆池等危险位置上，已由[smartcmd修复](https://github.com/BlocklyNukkit/PowerNukkitX/pull/4)）
3.[Issue#1290](https://github.com/PowerNukkit/PowerNukkit/issues/1290) （补充：该BUG可将白色染料当做骨粉使用，已由[CoolLoong修复](https://github.com/BlocklyNukkit/PowerNukkitX/pull/44)）
4.[Issue#1280](https://github.com/PowerNukkit/PowerNukkit/issues/1280)（补充：弩无法正常使用，已经由[lt-name修复](https://github.com/BlocklyNukkit/PowerNukkitX/pull/93)）
5.[Issue#1312](https://github.com/PowerNukkit/PowerNukkit/issues/1312)（补充：该BUG可用于刷可被活塞推动的方块）
6.[Issue#1306](https://github.com/PowerNukkit/PowerNukkit/issues/1306) （补充：该BUG可将被粘性活塞拉回的方块被可掉落的方块替换并移除）
7.[Issue#1321](https://github.com/PowerNukkit/PowerNukkit/issues/1321)（补充：由于一些原因，mojang将whitelist更名为allowlist，目前已同步更改，由[lt-name](https://github.com/BlocklyNukkit/PowerNukkitX/pull/132)合并[PN上游](https://github.com/PowerNukkit/PowerNukkit/pull/1327)并修改导入）
8.[Issue#1278](https://github.com/PowerNukkit/PowerNukkit/issues/1278)（补充：在观察者模式下只能缓慢飞行，在地面行走能听到脚步声）（在合并[NKX](https://github.com/CloudburstMC/Nukkit/pull/2007)的修改后修复）
9.[Issue#1292](https://github.com/PowerNukkit/PowerNukkit/issues/1292)（补充：使用磨石无法祛除装备上的附魔）

### ❌ 暂时被忽略或不修复的漏洞

暂时无法重现&存疑的漏洞
1.[Issue#1294](https://github.com/PowerNukkit/PowerNukkit/issues/1294)（补充：怪物死亡后的掉落物数量一致，可能是MobPlugin本身的问题）
2.[Issue#1307](https://github.com/PowerNukkit/PowerNukkit/issues/1307)（补充：使用鱼竿钓鱼钓出的附魔书无附魔属性）

### 💬 其他信息

如有发现更多PowerNukkit的BUG可在下方评论处补充

**Comment by terrifiedcn** [comment]
信标无法正常选择效果，选择后无效并消耗材料

**Comment by chencu5958** [comment]
> 信标无法正常选择效果，选择后无效并消耗材料

使用该[版本](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1818338687)进行测试时并未发现该问题，但满级信标给予的力量等级不对

**Comment by chencu5958** [comment]
> > 信标无法正常选择效果，选择后无效并消耗材料
> 
> 使用该[版本](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1818338687)进行测试时并未发现该问题，但满级信标给予的力量等级不对

test

**Comment by chencu5958** [comment]
> [Issue #1321](https://github.com/PowerNukkit/PowerNukkit/issues/1321) (WhiteList指令locale的key名有问题， [PullRequest #1327](https://github.com/PowerNukkit/PowerNukkit/pull/1327)应该可以修复这个问题)

已在Master分支，Git-1ea53c9中修复解决
