### ISSUE TITLE
The player appears after death in the same world in which he died

### ISSUE THREAD

**Issue by feanchy** [PowerNukkitX/PowerNukkitX#400]
# Video: [powernukkit/powernukkitx bug](https://www.youtube.com/watch?v=bWtu07HteaY&ab_channel=%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82%D0%B3%D1%83%D1%83%D0%B3%D0%BB)
 

### ✔ Expected Behavior
teleport after death to the world that is specified in server.properties as default

### ❌ Actual Behavior
the player appears after death in the same world in which he died

### 💬 Anything else we should know?
1) the same bug exists in powernukkit
2) this bug appeared after this addition - https://github.com/PowerNukkit/PowerNukkit/pull/677/files

**Comment by CoolLoong** [comment]
please you send your plugins list.According to my test,there is cannot repetitive.

**Comment by MonoAdrian23** [comment]
Works fine for me.

**Comment by feanchy** [comment]
> Пожалуйста, пришлите свой список плагинов. Согласно моему тесту, повторяться нельзя.
![Снимок](https://user-images.githubusercontent.com/50043944/174043874-897c8091-4a19-4cdb-aa45-a70c2f4ac960.PNG)

**Comment by MonoAdrian23** [comment]
WorldManager is the Problem

**Comment by Buddelbubi** [comment]
You can change the Respawn World in the /worldmanager settings menu.
