### ISSUE TITLE
the fruit of horus teleports in the water

### ISSUE THREAD

**Issue by feanchy** [PowerNukkitX/PowerNukkitX#401]
# Error Report
in vanilla minecraft, when you eat the fruit of horus under water, you don't teleport, in powernukkitx you teleport

### Screenshot or video
https://youtu.be/kZ06ApSM5uQ

### ### Expected behavior
the horus fruit should not teleport in water

### Actual behavior
the fruit of horus teleports in the water

**Comment by CoolLoong** [comment]
#406
