### ISSUE TITLE
nether does not load chunks

### ISSUE THREAD

**Issue by feanchy** [PowerNukkitX/PowerNukkitX#404]
#Error error report 
chunks in nether are not loade
![856783967343](https://user-images.githubusercontent.com/50043944/174149868-20d0b1e7-05f3-4917-9412-1aad9b73a573.png)
d (and so it is everywhere)

  ###Other information
  I tried deleting the world and restarting the server, it doesn't help

**Comment by smartcmd** [comment]
maybe there are some problems with VanillaGenerator, it's not the core bug
