### ISSUE TITLE
function命令相关问题

### ISSUE THREAD

**Issue by Superice666** [PowerNukkitX/PowerNukkitX#420]
# 🐞 错误汇报

- 不接受以`.function`为拓展名的文件
- 控制台语言文件错误
- 无法使用不完整的路径名执行funtion

**Comment by smartcmd** [comment]
1.官方的function文件的后缀名为.mcfunction而非.function
2.原版也不能用不完整路径,而且我没想明白实现这玩意有什么好处。。。
3.语言文件问题是因为nk的语言文件不完整
