### ISSUE TITLE
PlaceholderApi

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#423]
# ❇ Feature Request
 All These Plugins are Not supported.
Please add Compatibility with it.

**Comment by Superice666** [comment]
Thanks for your report! Could you please send us the errors?

**Comment by MonoAdrian23** [comment]
All Errors was send to "Plugins are Compatible with PowernukkitX" but i cant find this.

You can try to Check this by yourself.
Sorry

**Comment by CivicXFB** [comment]
Hello I have tested that the ScoreboardAPI can be started on the PNX server

**Comment by CivicXFB** [comment]
After a round of testing only the PlaceholderAPI, 2.1.1, is giving errors

**Comment by CoolLoong** [comment]
Please provide more information, you can always open this issue again
