### ISSUE TITLE
铁矿退出服务器后会变成更新方块

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#440]
# 🐞 错误汇报

### 📸 截图或视频
![VOW(B1HLMQR3EL GG3B6)YI](https://user-images.githubusercontent.com/22098995/178411698-af628ec0-2e47-4893-b35a-4a5a2169f707.png)

### ✔ 预期行为
正常铁矿

### ❌ 实际行为
更新方块

### 📋 Debug information
![image](https://user-images.githubusercontent.com/22098995/178411762-5040499d-99cf-4798-836b-2c90fead053e.png)

**Comment by Superice666** [comment]
请发送PNX构建版本并提供复现方式，实测当前master#906e1b92无法复现

**Comment by Superice666** [comment]
那个bnjs写的插件尚未针对PNX进行特化
