### ISSUE TITLE
严重的卡背包问题

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#452]
# 🐞 错误汇报

### 📸 截图或视频

https://user-images.githubusercontent.com/22098995/178891737-81515fbe-50dd-45d6-b86c-d822be4b9960.mp4

### ✔ 预期行为
正常

### ❌ 实际行为
不正常

### 💬 其他信息
版本
![)%T1MMX7VWLLACILCTPFNHF](https://user-images.githubusercontent.com/22098995/178891913-2b8a89de-191f-4627-bd70-e2ded457efa3.png)

**Comment by CoolLoong** [comment]
视频无法播放

**Comment by jlhsr** [comment]
已确认 该问题是pnx与bn冲突导致的 卸载bn即可解决
