### ISSUE TITLE
物品展示框内容物全部消失 右键就会回来

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#453]
# 🐞 错误汇报

### 📸 截图或视频
![image](https://user-images.githubusercontent.com/22098995/178894203-c2b0c3c4-a661-492a-853e-0401f865d897.png)

### ▶ 复现步骤
关服重启 进入世界 BUG出现

### 📋 Debug information
无

### 💬 其他信息

![91AF1J%42O}0`C6YRNI8T_E](https://user-images.githubusercontent.com/22098995/178894299-4055ba23-14cf-40c8-ab10-5558abd51dc3.png)

**Comment by Superice666** [comment]
mojang 1.19.10更新导致的客户端bug，等待mojang解决

**Comment by jlhsr** [comment]
感谢冰凉
