### ISSUE TITLE
不工作  player.getCraftingGrid().clearAll()

### ISSUE THREAD

**Issue by RuslanFF** [PowerNukkitX/PowerNukkitX#479]
# 🐞 错误汇报
👉 如果使用 player.getCraftingGrid().clearAll(); 清洁不起作用，但使用时 player.getCraftingGrid.clear(1, true);一切正常 

### ▶ 复现步骤
✍ 当使用 player.getCraftingGrid.clearAll();什么都没有被清除 

### ✔ 预期行为
✍ 使用 player.getCraftingGrid().clearAll(); 时应清除库存中的制作

### ❌ 实际行为
✍ 使用时不清洁库存中的工艺 player.getCraftingGrid().ClearAll(); 

### 💬 其他信息
✍ 当使用 player.getCraftingGrid().clear(1, true);一切正常

**Comment by Superice666** [comment]
感谢您的回复，这是由于`cn.nukkit.inventory.CraftingGrid`并不真的持有物品造成的，将会重写`clearAll`方法以解决此问题。
