### ISSUE TITLE
如果昵称中有3个或更多的空格，那么它会被允许到具有空昵称的服务器

### ISSUE THREAD

**Issue by RuslanFF** [PowerNukkitX/PowerNukkitX#486]
# 🐞 错误汇报

👉 如果昵称中有3个或更多的空格，那么它会被允许到具有空昵称的服务器

### ▶ 复现步骤
 ✍  如果昵称中有3个或更多的空格，那么它会被允许到具有空昵称的服务器

### ✔ 预期行为
 ✍ 不应使用空昵称输入

### ❌ 实际行为
✍如果昵称中有 2 或 1 个空格，则一切正常，服务器不允许昵称为空的玩家

### 💬 其他信息
✍ 如果昵称有 2 或 1 个空格，则一切正常，服务器不允许玩家使用空昵称，但如果有 3 个或更多空格，则服务器以空昵称进入

**Comment by Mcayear** [comment]
你是不是想说，玩家名字不能有3个空格及以上？

**Comment by RuslanFF** [comment]
不可以，如果玩家名字有3个或更多空格，那么服务器会以空名字进入

**Comment by Mcayear** [comment]
可以提供视频或者截图吗

**Comment by RuslanFF** [comment]
![Screenshot_2022-07-31-11-52-36-330](https://user-images.githubusercontent.com/49453275/182015861-24e41ea9-c698-4399-96f4-e03d6106ac16.jpeg)

**Comment by RuslanFF** [comment]
在minecraft的name字段中自己尝试，输入3个空格，然后去服务器

**Comment by smartcmd** [comment]
you can use eng :)

**Comment by RuslanFF** [comment]
Very good if it is possible to use English

**Comment by JustStevee** [comment]
О, лолгос, привет тебе от меня, нутелки, хиросо, и всех остальных, которые тебя так любят и уважают. Нутелка про тебя песенку спела:

"Знаешь, Руслан...", дальше сам знаешь.

С наилучшими пожеланиями, лавекон.

**Comment by JustStevee** [comment]
Привет, лолгос!

**Comment by KoshakMineDEV** [comment]
close this issue, fixed in #1138
