### ISSUE TITLE
在地狱中靠近岩浆的方块会自然起火

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#49]
# 🐞 错误汇报

在地狱中靠近岩浆方块会自然起火 原版需要打火石辅助

### 📸 截图或视频

原版生存的地狱
![屏幕截图 2022-02-10 125646](https://user-images.githubusercontent.com/61540722/153344984-55bc022d-028b-445c-ae53-1b4a20de6f97.png)
PowerNukkitX中地狱
![屏幕截图 2022-02-10 125113](https://user-images.githubusercontent.com/61540722/153345127-611c9b85-fd85-4b78-a012-7dead2bcf45a.png)

### ▶ 复现步骤

1.进入地狱找到与岩浆持平的方块

### ✔ 预期行为

不会起火.

### ❌ 实际行为

会起火

### 📋 Debug information

无
### 💢 错误堆栈或崩溃日志

无

### 💬 其他信息

使用powerNukkitX 新构建

**Comment by smartcmd** [comment]
经过测试，我似乎并没有遇到上述bug

**Comment by CivicXFB** [comment]
他需要周围有可燃烧的物品如果是绯红森林的话 他的艹以及树都会燃烧

**Comment by lt-name** [comment]
由 https://github.com/BlocklyNukkit/PowerNukkitX/pull/94 修复，等待再次检查

**Comment by CivicXFB** [comment]
已得到需要修复 但 地狱岩浆不在流动 使用 主分支#98

**Comment by CivicXFB** [comment]
![屏幕截图 2022-02-20 190405](https://user-images.githubusercontent.com/61540722/154839465-c77d584d-08dd-4db5-98b8-0be8e03e7403.png)
