### ISSUE TITLE
玩家进入服务器时无法显示表单

### ISSUE THREAD

**Issue by RuslanFF** [PowerNukkitX/PowerNukkitX#504]
# 🐞 错误汇报
👉使用了 PlayerJoinEvent 和表单，但是当玩家进入时没有出现表单

### ▶ 复现步骤
✍ 如果你使用 PlayerJoinEvent 来显示表单，那么什么都不会起作用并且表单不会出现

### ✔ 预期行为
 ✍ 使用 PlayerJoinEvent 时，当玩家进入时，应该会出现一个表单

### ❌ 实际行为
 ✍ 使用了 PlayerJoinEvent 和表单，但当玩家进入时什么都没有出现 

### 💬 其他信息
✍ 我使用了 PlayerJoinEvent 和表单，但是当玩家进入时什么都没有出现，控制台中没有错误

**Comment by Ootmnt150oO** [comment]
請使用 PlayerLocallyInitializedEvent

**Comment by RuslanFF** [comment]
非常感谢，现在我知道了
