### ISSUE TITLE
PetteriM1构建的nemisys子服插件在pnx上运行报错

### ISSUE THREAD

**Issue by Emotionalyear** [PowerNukkitX/PowerNukkitX#508]
# 🔌 Plugin compatibility issue

我使用PetteriM1构建的nemisys来搭建pnx的群组服，但当我进入大厅服务器时，它的的子服插件SynapseAPI在pnx上报错，导致我没办法进入服务器。

### 📸 Screenshots / Videos

<img width="1200" alt="屏幕截图 2022-08-07 234649" src="https://user-images.githubusercontent.com/89445415/183299593-b3a7fe27-5fb4-43e2-a245-3b646b592c5d.png">

<img width="1200" alt="屏幕截图 2022-08-07 234738" src="https://user-images.githubusercontent.com/89445415/183299596-97e118df-cb0b-4dee-b100-edbdfc6ecb1d.png">

### ▶ Steps to Reproduce

1.将SynapseAPI放入服务器插件文件夹
2.开启nemisys服务，并配置好文件
3.连接至服务器，出现报错，无法加入服务器

### 💬 Anything else we should know?

似乎只在pnx上出现这样的问题，nukkit上能够正常使用。应该是pnx添加了一些东西使它不兼容

**Comment by Emotionalyear** [comment]
抱歉第一段文字不小心删掉了
# 🔌 Plugin compatibility issue
<!-- 
我使用PetteriM1构建的nemisys来搭建pnx的群组服，但当我进入大厅服务器时，它的的子服插件SynapseAPI在pnx上报错，导致我没办法进入服务器。

**Comment by Emotionalyear** [comment]
抱歉第一段文字好像不见了
这里补充一下
我使用PetteriM1构建的nemisys来搭建pnx的群组服，但当我进入大厅服务器时，它的的子服插件SynapseAPI在pnx上报错，导致我没办法进入服务器。

**Comment by smartcmd** [comment]
收到

**Comment by Superice666** [comment]
编译时使用了错误签名的依赖，PNX无法也不可能解决此问题
