### ISSUE TITLE
海草会生成在一格高的水面把水覆盖

### ISSUE THREAD

**Issue by givegrandpaclimb** [PowerNukkitX/PowerNukkitX#509]
海草会生成在一格高的水面把水覆盖
![GL9976ZC3ZSD2Z_6XQSK$WV](https://user-images.githubusercontent.com/78897586/183320242-219b6c15-18ec-4186-9995-7ad36563d024.jpg)

**Comment by CivicXFB** [comment]
这是基岩渲染龙BUG原版也有

**Comment by Superice666** [comment]
确认是客户端问题，无法修复
