### ISSUE TITLE
如果您使用 termux 运行 powernukkitx，它将无法启动

### ISSUE THREAD

**Issue by RuslanFF** [PowerNukkitX/PowerNukkitX#520]
# 🐞 错误汇报

### 📸 截图或视频
✍ https://imgur.com/a/Pb2zwHJ

### ▶ 复现步骤
✍当我通过 Termux 运行 PowerNukkitX 1.19.10-r1 或 1.19.20-r1 时，它没有启动并给出错误，但是当我通过 termux 运行 PowerNukkitX 1.6.0.0-PNX 时，一切都启动并正常工作

**Comment by Superice666** [comment]
Now we use JNA to monitor pnx performance data and optmize some functions using the data. It seems that JNA does not supports Android.

**Comment by Superice666** [comment]
Can you run with administrator privileges (sudo) ?

**Comment by RuslanFF** [comment]
不幸的是，我无法以管理员权限运行它。

**Comment by Superice666** [comment]
@RuslanFF 请问您现在可以尝试一下PR #532 是否可以解决您的问题吗？感谢！

**Comment by RuslanFF** [comment]
没有帮助 https://imgur.com/a/CfT7EvM

**Comment by Superice666** [comment]
@RuslanFF Are you using `git-[e041149](https://github.com/PowerNukkitX/PowerNukkitX/pull/532/commits/e041149e397eee3959073de436dbc507ebc0b125)` from this [CI build](https://github.com/PowerNukkitX/PowerNukkitX/runs/7817838637?check_suite_focus=true)?

**Comment by RuslanFF** [comment]
https://imgur.com/a/nHIzNZo 正确的？

**Comment by Superice666** [comment]
我刚刚更新了PR #532 ，请问现在可以解决此问题吗？

**Comment by RuslanFF** [comment]
非常感谢一切正常！https://imgur.com/a/cv9acUN

**Comment by Superice666** [comment]
同样感谢您的报告！感谢支持。
