### ISSUE TITLE
请支持修改自定义服务器踢出提示

### ISSUE THREAD

**Issue by SOURsLEMONS** [PowerNukkitX/PowerNukkitX#521]
![EZ`O A)IS0V`N_7A}90%JKY](https://user-images.githubusercontent.com/89817084/184151659-8c9f3f37-58a6-44cf-87f8-365e4ca8bcd9.png)
如图，是pnx玩家无白名单被踢出服务器的提示，无法对修改请求可以自定义修改该内容
如果可以的话，请支持更多内容修改
客户端过期，服务端过期等等

**Comment by CoolLoong** [comment]
不考虑实现，请通过插件实现

**Comment by SOURsLEMONS** [comment]
在原版中至少是提示为中文，你未邀请游戏
请求提供一个可供服主修改的，语言文件
