### ISSUE TITLE
Azaleas not dropping

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#538]
# 🐞 bug report
 

 ### 📸 Screenshot or video
 

https://user-images.githubusercontent.com/56545793/184682621-53b5ab07-6903-444a-ab2a-5183a902fe63.mp4

 ### ▶ Steps to reproduce
 
Get some azaleas, place them down and break them.

 ### ✔ Expected behavior
 
Drop rate for azaleas should be 100%

 ### ❌ Actual behavior
 
Azaleas aren't dropping always (see clip)

 ### 📋 Debug information
 
/

 ### 💢 Error stack or crash log
 
/

 ### 💬 Additional Information
 
/

**Comment by CoolLoong** [comment]
What is your version

**Comment by TraxTRL** [comment]
> What is your version

We're using 1.19.20-r2.
