### ISSUE TITLE
Missing wood recipes 

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#539]
# 🐞 bug report
 

 ### 📸 Screenshot or video
 
![35bffcc0-cd69-4ce5-b7c0-ae8bd4cf0855](https://user-images.githubusercontent.com/56545793/184541177-80b85c05-39b5-4f06-8d47-0a256a342611.png)
![ffd06682-8b36-4f55-b997-c51e82753bcd](https://user-images.githubusercontent.com/56545793/184541185-51bf3e8d-5b85-41f1-bbc9-3e297690b76c.png)
![9c0eb3eb-304a-4570-bf32-01726dfa5e4f](https://user-images.githubusercontent.com/56545793/184541191-84a9ad0f-b07e-4277-a80e-5ad3566581c5.png)
![04cf17be-eb19-44e3-8ad1-13e65b39a15c](https://user-images.githubusercontent.com/56545793/184557127-0ba5e1d9-5ad1-4483-8b6a-2bb5e1649080.png)

 ### ▶ Steps to reproduce
 
Take a type of log and use it to make all-sided logs (see screenshot 2 & 3)

 ### ✔ Expected behavior
 
Putting 4 logs together will give you 3 all-sided textured logs of the type of wood you used to craft.

 ### ❌ Actual behavior
 
Instead, you always get the Oak Log variant of the all-sided textured log. This is also for fences (see screenshot 4).
Mangrove log recipes are completely missing (see screenshot 1).

 ### 📋 Debug information
 
/

 ### 💢 Error stack or crash log
 
/

 ### 💬 Additional Information
 
/

**Comment by Buddelbubi** [comment]
![grafik](https://user-images.githubusercontent.com/44944269/187675493-a1dac46d-6478-439c-b7a5-5b522137265b.png)
Fences are still bugged!

**Comment by CoolLoong** [comment]
in [1.19.21-r1](https://github.com/PowerNukkitX/PowerNukkitX/releases/tag/1.19.21-r1)

**Comment by CoolLoong** [comment]
![)NQNJE9YY%B@6T0)BPGNWZC](https://user-images.githubusercontent.com/69153398/187683482-96f418b1-eda5-48d7-9e47-f6c4dc7176bb.png)
