### ISSUE TITLE
Loom and Cartography Table not working 

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#540]
# 🐞 bug report
 

 ### 📸 Screenshot or video
 
![29848928-d1fd-4aff-93dd-3884089ff077](https://user-images.githubusercontent.com/56545793/184542000-1316aae2-cb85-45c0-8559-34bf3db4fad9.png)
![25e8b496-50d6-4424-807d-ae81c8f12879](https://user-images.githubusercontent.com/56545793/184542002-485e36bc-2112-497e-86f5-26e365cc5c5f.png)

 ### ▶ Steps to reproduce
 
Get a loom and cartography table and try to interact with them.

 ### ✔ Expected behavior
 
An interface should open like in the attached screenshots.

 ### ❌ Actual behavior
 
Instead nothing happens when you interact with one of them.

 ### 📋 Debug information
 
/

 ### 💢 Error stack or crash log
 
/

 ### 💬 Additional Information
 
/

**Comment by CoolLoong** [comment]
#312
