### ISSUE TITLE
Entities below -16 will die

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#545]
# 🐞 bug report
 

 ### 📸 Screenshot or video
 

https://user-images.githubusercontent.com/56545793/184682224-78981abb-9390-4970-8f3d-27d9434f1359.mp4

https://user-images.githubusercontent.com/56545793/184682255-99604c0b-6336-4a76-af7b-596d35a2fc91.mp4

 ### ▶ Steps to reproduce
 
Spawn an entity below -16.

 ### ✔ Expected behavior
 
Entity dies below -80.

 ### ❌ Actual behavior
 
Entity dies below -16.

 ### 📋 Debug information
 
 /

 ### 💢 Error stack or crash log
 
 /

 ### 💬 Additional Information
 
 For some reason, players don't take damage below -16.

**Comment by Mcayear** [comment]
补充：y在0以下的非玩家生物都会收到伤害
