### ISSUE TITLE
OutOfMemory error in CompoundTag

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#551]
1. CompoundTag的toSnbt与toString在解析大型文件时（135MB的mcstructure文件）会将内存吞噬殆尽。

2. 但PNX的NBTIO.read()读取文件时能正常生成CompoundTag。

**Comment by Mcayear** [comment]
mcstructure文件压缩包：https://ayear.lanzouv.com/iTr6v0bkom3g[https://ayear.lanzouv.com/iTr6v0bkom3g](https://ayear.lanzouv.com/iTr6v0bkom3g)

**Comment by CoolLoong** [comment]
Cannot fix
