### ISSUE TITLE
希望可以还原对于骑马交互上的原版特性

### ISSUE THREAD

**Issue by lthuas** [PowerNukkitX/PowerNukkitX#559]
# ❇ Feature Request

**Comment by lthuas** [comment]
我内容是因为格式错误被吞掉了嘛QVQ

**Comment by lthuas** [comment]
不好意思不好意思内容被吞掉了qwq我重新写

**Comment by lthuas** [comment]
在原版中，未驯养的马与驴与骡子可以右击骑上（骑上后可以不断尝试驯养，如失败则跌落，成功则冒出爱心），且驯服后按e可以打开马与驴与骡子的背包，在里面可以装上鞍，马铠（马凯只限马），可以长按空格蓄力跳跃。在pnx服务器当中，未驯养的马与驴与骡子右击无法骑上，并且拿出鞍右击马与驴与骡子则直接套上可以进行骑行操作，没有马与驴与骡子的背包界面，也无法空格跳跃，空格会跌落ouo

**Comment by CoolLoong** [comment]
部分完成
