### ISSUE TITLE
Missing feature for Minecart with Hopper 

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#560]
https://user-images.githubusercontent.com/56545793/184907235-340f4669-3868-4d07-b40d-07c090cf7690.mp4

### Steps to Reproduce
Get a minecart with hopper and throw stuff on it. 

### Expected Behavior
The minecart with hopper collects the item like a hopper does and gives it to a container below itself.

### Actual Behavior
Minecart with hopper isn't working. You can only put items in it.

**Comment by Mcayear** [comment]
#507
