### ISSUE TITLE
Piston is pushing bamboo

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#561]
# Bug report

https://user-images.githubusercontent.com/56545793/184949323-2a5c4cd9-8b13-4d0d-9b1b-232c2e7c982e.mp4

### Steps to Reproduce
Place a piston next to bamboo and push the bamboo.

### Expected Behavior
Bamboo breaks and drops, no blocks are pushed.

### Actual Behavior
Bamboo is first pushed, then breaks and drops.

**Comment by smartcmd** [comment]
fixed
