### ISSUE TITLE
Items in glow item frames disappear visually

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#577]
# Bug report

![Screenshot_20220818-160243_Xbox Beta](https://user-images.githubusercontent.com/56545793/185415005-2c9b9b7f-d11b-4de8-9ece-2f4447c3d1cf.png)
![Screenshot_20220818-160219_Xbox Beta](https://user-images.githubusercontent.com/56545793/185415031-b9108e0b-17ef-4b46-8907-4e9a93085ee0.png)

### Steps to Reproduce

Place down glow item frames and put items in them. Now rejoin server or switch worlds and check the glow item frames.

### Expected Behavior

Item remains visible.

### Actual Behavior

Item becomes invisible.

**Comment by CoolLoong** [comment]
This is a client-side bug
