### ISSUE TITLE
磨石无法正常使用

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#579]
工具无法消除附魔效果 而是返回背包

**Comment by lthuas** [comment]
补充：（纯净客户端测试）随意附魔1件工具或装备，放入磨石的第一格，右边会显示去除附魔的装备，取出放入背包后，重新返回了那件附魔的装备/工具进入背包，没有去除附魔。希望可以实现去除成功返回背包去除后的装备工具，非常感谢~

**Comment by lthuas** [comment]
> 补充：（纯净客户端测试）随意附魔1件工具或装备，放入磨石的第一格，右边会显示去除附魔的装备，取出放入背包后，重新返回了那件附魔的装备/工具进入背包，没有去除附魔。希望可以实现去除成功返回背包去除后的装备工具，非常感谢~

发布1.19.20-r5 (#576) PowerNukkitX #2602这个版本的pnx核心

**Comment by chencu5958** [comment]
@CoolLoong 这个BUG是确定可以复现的，因为这个BUG的来源就是源自于PowerNukkit那边，现象我在issues #40 中有提到过
