### ISSUE TITLE
钓鱼竿会掉到无附魔属性的附魔书

### ISSUE THREAD

**Issue by lthuas** [PowerNukkitX/PowerNukkitX#588]
# 🤷‍♀️ I have a question

【出现的问题现象】在玩家钓鱼的过程中一位钓鱼玩家钓到了一本无附魔属性的附魔书，随后向其他原版玩家询问说是附魔书只会钓到有属性的，并不会出现无附魔属性的附魔书，后面那位玩家又钓到一本也是无属性，希望可以钓到有属性的附魔书，不会钓到无属性的
【运行测试的环境】有安装功能性插件（但无涉及到钓鱼竿类地形等可能受影响的插件）的服务器，核实起来较难qwq，无法确定滴话我在删除这条反馈叭
【无后台报错】

### 📸 Screenshots / Videos

![37Y8@Q@ A15UE%LSUU){XUC](https://user-images.githubusercontent.com/99377251/185736344-39c4065f-3016-4de7-907d-907724c023f3.jpg)
![3H~ OHNP$~)@J66TR} QO](https://user-images.githubusercontent.com/99377251/185736358-4d128451-5ec3-4ebc-8727-450eb3b1422b.jpg)
### 📋 Debug information

* PowerNukkitX version: 发布1.19.20-r5 (#576) PowerNukkitX #2602
* Debug link: ✍

**Comment by lthuas** [comment]
使用的普通鱼竿和附魔鱼竿钓出的

**Comment by lthuas** [comment]
这条反馈刚说完又钓出一本附魔属性的书本QW
![7X0S_YS2{A_E O9P3$D)NLW](https://user-images.githubusercontent.com/99377251/185736498-9bc0d287-84a5-48f9-bc24-1467968393fd.jpg)
Q

**Comment by lt-name** [comment]
经检查pnx内部获取钓鱼结果物品直接使用了物品id，但附魔书参数存储在nbt，这导致附魔书无法正常使用
