### ISSUE TITLE
盾牌格挡效果不能被取消

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#597]
# 🐞 错误汇报
cn.nukkit.event.entity.EntityDamageBlockedEvent
setCancelled(false)
不能阻止盾牌的格挡效果（

### 📸 截图或视频
![Screenshot_20220824_140555_com mojang minecraftpe](https://user-images.githubusercontent.com/48203962/186343606-28a7ef08-bbde-4df3-a80c-f59de2c95695.jpg)

### ✔ 预期行为

取消格挡效果，即使玩家使用盾牌蹲下也会收到伤害。

### ❌ 实际行为

在拦截事件的情况下，盾牌正常生效

### 💬 其他信息

盾牌不应该为全范围保护，目前任意方向的攻击都会被格挡。

**Comment by Superice666** [comment]
插件问题，与核心无关
