### ISSUE TITLE
活塞臂推出变更新方块

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#604]
![AKHUF0@QFV1(QJ~GOXMK~6N](https://user-images.githubusercontent.com/22098995/186888240-aae6eb5f-2d2e-4d55-ab4b-653ed4e06cee.png)
![image](https://user-images.githubusercontent.com/22098995/186889456-c455e317-2e16-46db-866e-c073e6cb9929.png)

**Comment by Superice666** [comment]
在 58a6a42292f10d8f06165f714ec1fce112c464ae 上无法复现
