### ISSUE TITLE
Effect Duration Bug

### ISSUE THREAD

**Issue by CoroxMyName** [PowerNukkitX/PowerNukkitX#614]
# 🐞 Effect Duration Bug

When giving all players an effect by typing _/effect @a haste 60 1 true_ for example, it should give every player the haste effect for 60 seconds of an amplifier of 1. But in reality it gives everyone the haste effect which only lasts for 30 seconds instead of 60. We've noticed that the real duration depends on the given duration (in this case 60 seconds) and on the players currently playing on the server (in this case 2). The reason for this bug is that the given duration is getting divided by the current player count. So in this case the given duration (60 seconds) got divided by the player count (2) which ended up in only a real duration of 30 seconds. This applies to every given duration, every player count and every effect.

### ▶ https://user-images.githubusercontent.com/96849286/187275330-fd1b6528-5801-4e2b-af27-c108709f8095.mp4

Typing _/effect @a haste 60 1 true_ in chat while the player count is higher than 1. Then look how long the effect lasts

**Comment by smartcmd** [comment]
fixed
