### ISSUE TITLE
How do I load my 1.19 world on pnx?

### ISSUE THREAD

**Issue by jameshackerbond** [PowerNukkitX/PowerNukkitX#619]
# 🤷‍♀️ I have a question

How can I load my minecraft bedrock 1.19 world on a pnx server?

### 📋 Debug information

* PowerNukkitX version: ✍
* Debug link: ✍

**Comment by smartcmd** [comment]
chunker.app
and, do not ask question here

**Comment by jameshackerbond** [comment]
> chunker.app and, do not ask question here

I tried that but concrete turned into observers and structure blocks I'll send some screenshots
