### ISSUE TITLE
发光鱿鱼掉落普通墨囊

### ISSUE THREAD

**Issue by Pigeon2333** [PowerNukkitX/PowerNukkitX#624]
# 🐞 错误汇报
发光鱿鱼掉落普通墨囊
👉 尽可能详实地描述错误信息
击杀发光鱿鱼掉落的是普通的墨囊

### 📸 截图或视频
![image](https://user-images.githubusercontent.com/68182691/188268931-7adf57a9-c574-4fa5-9597-20baec1a34f0.png)

### ▶ 复现步骤
1.寻找或生成一只发光鱿鱼
2.杀死它
3.掉落墨囊

### ✔ 预期行为
应当掉落发光墨囊

### ❌ 实际行为
掉落的是普通墨囊

### 📋 Debug information
我觉得好像没必要。。。

### 💢 错误堆栈或崩溃日志
无

### 💬 其他信息
无

**Comment by CivicXFB** [comment]
pnx 应该没实现这个生物吧

**Comment by smartcmd** [comment]
是mobp插件bug，pnx核心都还没实现这玩意。。。
