### ISSUE TITLE
Minecart with Hopper.

### ISSUE THREAD

**Issue by YucaHammer** [PowerNukkitX/PowerNukkitX#627]
The Minecart with a Hopper doesnt collect the items.

![Screenshot (25)](https://user-images.githubusercontent.com/111245394/188286704-9bb22fe5-8f36-40d6-9b9c-a7abf680512f.png)

Place a Minecart with a Hopper and drop a Item on it.

The Minecart has to collect the item.

The Minecart doesnt collect the Item.

**Comment by smartcmd** [comment]
https://github.com/PowerNukkitX/PowerNukkitX/pull/635
