### ISSUE TITLE
Items in Glow Item Frames become invisible

### ISSUE THREAD

**Issue by YucaHammer** [PowerNukkitX/PowerNukkitX#628]
# 🐞 If you place items in a glowing item frame and then walk away a little and walk back, the item is invisible.

**Comment by Superice666** [comment]
This is a client bug. Wait for mojang to fix.

**Comment by CoolLoong** [comment]
> This is a client bug. Wait for mojang to fix.

bds没有这个Bug

**Comment by Superice666** [comment]
> > This is a client bug. Wait for mojang to fix.
> 
> bds没有这个Bug

如果强制bds不使用新区块协议，一样会有这个bug

**Comment by CoolLoong** [comment]
> > > This is a client bug. Wait for mojang to fix.
> > 
> > 
> > bds没有这个Bug
> 
> 如果强制bds不使用新区块协议，一样会有这个bug

有没有办法能够修复这个问题(hack实现也可以)，我觉得等待mojang基岩版修复，不知道要等到什么时候

**Comment by Superice666** [comment]
@CoolLoong 不如先修复其他的bug
