### ISSUE TITLE
垂滴叶无法正常下垂

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#655]
![HZD_DZEH7} K(__SXC3ZXQK](https://user-images.githubusercontent.com/22098995/189516653-d6c2c6f1-bc8b-4987-85b1-5a8a70fa4460.png)

**Comment by jlhsr** [comment]
玩家站在上面时 叶子不动

**Comment by CoolLoong** [comment]
服务端无法复现，请检查是否为插件问题
