### ISSUE TITLE
Piston can push portal

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#659]
# 🐞 bug report
 
![062355e4-de9a-4094-ab95-c5479ef2547f](https://user-images.githubusercontent.com/56545793/189532917-3c5984ee-2e2a-4449-94ee-4dda8f5528a4.png)

 ### ▶ Steps to reproduce
 
Place a piston next to a nether portal and activate the piston.

 ### ✔ Expected behavior
 
Nothing happens.

 ### ❌ Actual behavior
 
Portal gets pushed.

**Comment by smartcmd** [comment]
fixed in the newest ver
