### ISSUE TITLE
Slow flying in spectator mode

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#671]
# 🤷‍♀️ I have a question

Issue #125 has been marked as fixed. However, you still fly slowly in spectator mode. Is that intentional?

**Comment by CoolLoong** [comment]
Here as with NukkitX, we just synchronized the upstream changes

**Comment by TraxTRL** [comment]
> Here as with NukkitX, we just synchronized the upstream changes

So you won't fix the slow flying in spectator mode?

**Comment by CoolLoong** [comment]
I think this is consistent with the vanilla.
