### ISSUE TITLE
Nemisys Support

### ISSUE THREAD

**Issue by megatron0001** [PowerNukkitX/PowerNukkitX#687]
# ❇ Feature Request
Nemisys Support for PNX because my network runs on nemisys and I can't switch to WDPE

### 📸 Screenshots / Videos
None really just wondering if nemisys is supported

**Comment by lt-name** [comment]
I personally don't think pnx should be modified to be compatible with nemisys
Should modify nemisys to be compatible with pnx
The way nemisys works makes it susceptible to compatibility issues
