### ISSUE TITLE
/gamerule do not work!

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#689]
# 🐞 错误汇报
在原版中使用`/gamerule sendcommandfeedback false`命令可以关闭命令执行的反馈。（通常是白字信息）
在PNX中它不工作。

### 📸 截图或视频
在PNX中：
![Screenshot_20221001_175227_com mojang minecraftpe](https://user-images.githubusercontent.com/48203962/193404098-0a8009b9-3b3e-48db-9527-a186799d9358.jpg)
在原版中：
![Screenshot_20221001_175826_com mojang minecraftpe](https://user-images.githubusercontent.com/48203962/193404121-2899679f-124a-4d4b-9d28-763cc3ec6acc.jpg)

### ▶ 复现步骤
/gamerule sendcommandfeedback false
/particle minecraft:villager_happy ~~~
此时不应该有任何白字提示

### ❌ 实际行为
游戏规则没有成功拦截命令反馈（通常为白字）

**Comment by lt-name** [comment]
pnx内部暂时没加这个规则的判断
