### ISSUE TITLE
Remove /reload from PowernukkitX 

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#697]
# ❇ Feature Request
 /reload can break many plugins.
Noone should use It.
I know, many Users can block this CMD but its not more useful for new Users.
Pocketmine haves remove the /reload command.

**Comment by Superice666** [comment]
Actually, whether or not is a really hard choice for the dev team including myself. I think we need more people's opinions and more reasons about why we really should remove it.

**Comment by MonoAdrian23** [comment]
Its perfect for discussion i think.
But Most important is, it can break many plugins like Plotsquared, Multiworld, WorldManager and many Others.

**Comment by jlhsr** [comment]
The fact that most of the server plugins are good Reload is important because it can update without the player falling offline

**Comment by MonoAdrian23** [comment]
@jlhsr 

I think Players fall offline its not a big thing.
Its much more important that Plugins works perfectly.

**Comment by CivicXFB** [comment]
I think restart is necessary. All computers are powered on, restarted and shut down. If you delete restart, many things will be lost. If plug-ins are not compatible, you should let them adapt instead of deleting them

**Comment by MonoAdrian23** [comment]
@CivicXFB Noone should delete restart.
We mean /reload
Reload haves nothing to do with a full restart.

**Comment by CoolLoong** [comment]
I don't agree with removing this command, I think reload is important and plugins should to adapt reload themselves. If the plugin will be broken by reload command, then you should not use this command instead of just delete this command.

**Comment by Buddelbubi** [comment]
WorldManager should not break on reload

**Comment by CoolLoong** [comment]
> WorldManager should not break on reload

Use /reload plugin to reload the specified plugin
