### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by feanchy** [PowerNukkitX/PowerNukkitX#704]
[20221007195047_NullPointerException.md](https://github.com/PowerNukkitX/PowerNukkitX/files/9735768/20221007195047_NullPointerException.md)

**Comment by CoolLoong** [comment]
Can you provide more information, such as the plugina you use?

**Comment by feanchy** [comment]
> Можете ли вы предоставить дополнительную информацию, например, какие плагины вы используете?

vanillagenerator

**Comment by CoolLoong** [comment]
I don't have problems with the latest version of vg. If there is more, feel free to reopen issue
