### ISSUE TITLE
setImmobile 在当前AI框架中未实现

### ISSUE THREAD

**Issue by Superice666** [PowerNukkitX/PowerNukkitX#707]
# 🐞 错误汇报

setImmobile未被正确处理

**Comment by CoolLoong** [comment]
![image](https://user-images.githubusercontent.com/69153398/195340132-40e2959f-2908-4abe-8022-426ce98f0dad.png)

**Comment by Superice666** [comment]
setImmobile产生的影响未在ai运算中被考虑实现，重新打开此问题

**Comment by CoolLoong** [comment]
抱歉，只测试了玩家，对玩家是生效的
