### ISSUE TITLE
Player#kill(); causing Server crash

### ISSUE THREAD

**Issue by KayllonDouglas** [PowerNukkitX/PowerNukkitX#742]
As the title says, whenever I use the `kill()` method of the `Player` class the server crashes, at the moment I am using it in the `PlayerQuitEvent` event.

- Image of the exception that occurred:

![Screenshot_2022-10-25-22-13-18-348-edit_com android chrome](https://user-images.githubusercontent.com/76278156/197912079-eb1cdd24-017c-40eb-b430-a3aa9b1a2234.jpg)
 
- My code:
![Screenshot_2022-10-25-23-07-31-429-edit_com termux](https://user-images.githubusercontent.com/76278156/197918461-2d603d83-dc62-40e4-ba23-d9a2a1994edf.jpg)

- Log File: 

[server.log](https://github.com/PowerNukkitX/PowerNukkitX/files/9865144/server.log)

It may seem strange but it is this method that is giving me a problem, I will test more and provide more information

**Comment by KayllonDouglas** [comment]
`Player#close()` method is also happening, with all arguments filled

 - My code:
 
![Screenshot_2022-10-25-22-41-16-762-edit_com termux](https://user-images.githubusercontent.com/76278156/197914954-1a378716-9910-47c4-882c-852b47db9ac3.jpg)

- Console Log:
![Screenshot_2022-10-25-22-39-22-271-edit_com android chrome](https://user-images.githubusercontent.com/76278156/197915006-91c28dfc-54b9-41f4-862d-cf8be1d74518.jpg)

- Log File: 
[server.log](https://github.com/PowerNukkitX/PowerNukkitX/files/9865248/server.log)

**Comment by CoolLoong** [comment]
?
