### ISSUE TITLE
Installation without Cli

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#754]
# ❇ Feature Request
 Is there a way to Install this without Cli?
Many Server hosters (Gameserver) havent a Command tool for Windows or Linux.

**Comment by MonoAdrian23** [comment]
Invalid start filed detected, please use PNX-CLI to start if you aren't a developer.

I have Download PowernukkitX Full, and have Install PowernukkitX.jar

But this Happens.

**Comment by CoolLoong** [comment]
If cli cannot be used, you can use the startup command. (PNX cannot be used on a service provider that does not support JVM startup parameters)
Please read https://github.com/PowerNukkitX/PowerNukkitX#steps

**Comment by MonoAdrian23** [comment]
Windows or Linux Commands cant be used for Gameserver.
Only for V-Server

**Comment by CoolLoong** [comment]
It is not a Windows or Linux command. You only need to add JVM startup parameters, which is the key

**Comment by CoolLoong** [comment]
If your server can only be started with java -jar xxx, PNX does not support this server.

**Comment by MonoAdrian23** [comment]
Bruh OK.
Thanks

**Comment by MonoAdrian23** [comment]
Whaaat!
This is great!
A Gameserver only haves a Start, Stop and Kill Button.
Like Minehub Server Hoster

**Comment by CoolLoong** [comment]
Do you have a discord, when I finish I need to test it and contact you via discord.

**Comment by MonoAdrian23** [comment]
No i havent

**Comment by CoolLoong** [comment]
Please sign up if you need to use it, github is not a good way to contact you
