### ISSUE TITLE
when I got on the boat suddenly the boat sank

### ISSUE THREAD

**Issue by AraaCuteUwU** [PowerNukkitX/PowerNukkitX#768]
https://user-images.githubusercontent.com/71029264/200172390-9ac9df6d-4c70-4aaa-a51d-d86d6aa68182.mp4

**Comment by CivicXFB** [comment]
After several rounds of testing it was found that NukkitX had the same problem due to changes made to the ship by 1.19.40mojang.

**Comment by CivicXFB** [comment]
I rolled back the version to 1.19.31 without any problems
