### ISSUE TITLE
梯子bug

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#790]
# 🐞 错误汇报

当使用NK系列点击楼梯无法在左后出现楼梯，而是生成的幽灵楼梯
![3{20%L1SBJFB70WKVZXJ12P](https://user-images.githubusercontent.com/61540722/202416967-73888ce9-15cc-4352-9e8b-3cfd0f629da5.png)

### ✔ 预期行为

原版是能放置正常楼梯

### ❌ 实际行为

生成的是幽灵楼梯

**Comment by CivicXFB** [comment]
server-authoritative-movement=server-auth
server-authoritative-block-breaking=on
开启状态也是生成幽灵楼梯

**Comment by CoolLoong** [comment]
不理解是什么意思，给出详细明确的复现步骤
