### ISSUE TITLE
內建新增多世界傳送指令

### ISSUE THREAD

**Issue by tmnt150** [PowerNukkitX/PowerNukkitX#791]
# ❇ 特性请求

**Comment by smartcmd** [comment]
待会加个
现在你可以使用execute in world_name run tp ~ ~ ~实现同样效果

**Comment by CoolLoong** [comment]
> 待会加个 现在你可以使用execute in world_name run tp ~ ~ ~实现同样效果

建议不添加 execute in明显更好用
