### ISSUE TITLE
PNX-CLI的下载URL地址在linux/Unix下不可用

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [PowerNukkitX/PowerNukkitX#800]
# 🐞 错误汇报

如题，原来的jre环境地址已经不可用，且不能跳过下载环节。
### ▶ 复现步骤

在ubuntu 20.02下下载PNX-CLI，并使用graalvm环境启动，会要求选择下载jvm，随意选择一个。

### ✔ 预期行为

下载完毕后成功解压，开始启动。

### ❌ 实际行为

运行后开始下载时，2个jvm地址均为写死，**且无跳过选项和参数**。
> cat tmp.zip或.gz
均会输出404 not found，这导致无法成功解压。

### 💬 其他信息

善用github的/latest/，提供跳过下载，并增加检测当前jvm的能力。

**Comment by Superice666** [comment]
1. fastgit和cnpmjs貌似已经停止下载代理服务导致出现问题
2. /latest/无法被远程主机成功解析
3. 如果已经安装了JVM会复用已经安装完成的，除非版本不正确，java18+检测失败问题已经被提出了
4. 你没有提供PNX-CLI版本，请使用`pnx -V`指令提供pnx解释器版本
5. 大概率你在使用远古版本的pnx-cli，自0.0.6以后PNX-CLI的行为就并非只提供两个写死的JVM下载地址了，目前最新版本为0.0.8-pre
