### ISSUE TITLE
Calcite cannot be burned

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#807]
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://user-images.githubusercontent.com/56545793/204101876-42f0dd3e-588c-4e99-a49e-b5ab9ce30959.mp4

### ▶ Steps to Reproduce

1. Get Calcite and flint & steel
2. Make a fire
3. Throw the Calcite into the fire
4. Extinguish the fire
5. Try to collect the item

### ✔ Expected Behavior

Item disappeared completely 

### ❌ Actual Behavior
Item disappeared visually 

### 📋 Debug information

* PowerNukkit version: 1.19.40-r2
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by CoolLoong** [comment]
Calcite can be burned in vanilla

**Comment by TraxTRL** [comment]
> Calcite can be burned in vanilla

Yes, that's why I reported it.

**Comment by CoolLoong** [comment]
> Item disappeared visually

sorry,i not careful reading
