### ISSUE TITLE
关服报错🐞

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#812]
# 🐞 错误汇报
https://github.com/PowerNukkitX/PowerNukkitX/actions/runs/3562121810
👉🐞  换上新核心后卡进服界面
![YV47LTBA`6{QVBM5QJQH7 U](https://user-images.githubusercontent.com/22098995/204283597-d18321b6-6571-410e-b701-bc84a806b2f7.png)

### 📸🐞  
![A $4J6%F1 OXW30`T3GZW27](https://user-images.githubusercontent.com/22098995/204284274-6d874634-bdab-4174-94e8-a2cd4ea0f64e.png)
 

### ▶ 🐞 关服报错
![72XCQPWKH@PY%{U4EQBT0{N](https://user-images.githubusercontent.com/22098995/204283820-d7764110-85e2-4b19-bcfe-c4017c4c742a.png)

**Comment by CoolLoong** [comment]
给稳定复现的方法，或者提供存档等测试环境，否则关闭issue

**Comment by jlhsr** [comment]
复现办法：安装两个插件其中一个

**Comment by jlhsr** [comment]
FastAsyncWorldEdit-pnx.jar
ChiliShop-1.0-SNAPSHOT.jar

**Comment by jlhsr** [comment]
通过人工排查 删除这两个插件服务器可以正常进入

**Comment by CoolLoong** [comment]
下面的报错应该是你没开启bstats，这个npe后面会修复。至于进不了服，我明天有时间测试一下

**Comment by CoolLoong** [comment]
> 通过人工排查 删除这两个插件服务器可以正常进入

无法复现
