### ISSUE TITLE
红树苗悬挂状态未知

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#813]
# 🐞 错误汇报
我开服发现
20:43:51 [ERROR] Found an unknown BlockId:Meta combination: 731:0 - minecraft:mangrove_propagule_hanging;hanging=0;propagule_stage=0 - BlockProperties{bitSize=4, properties=[0-1:hanging, 1-4:propagule_stage]} - minecraft:mangrove_propagule_hanging, trying to repair or replacing with an "UPDATE!" block.
这个错误，我查阅相关wiki并未了解这是什么东西，查看代码库发现确实是有这个块

### 💬 其他信息
使用版本 
20:43:45 [INFO ] 此服务器正在运行 Nukkit 1.19.40-r3 (git-0d14c11d1) 版本 "PowerNukkitX" (API 1.0.14)

**Comment by jlhsr** [comment]
🐞遇到同样问题

![MG}BIOIP_%_@I7LQG@%_335](https://user-images.githubusercontent.com/22098995/204284609-65403c83-2c59-43dd-8e69-4d4f9556b648.png)

**Comment by CoolLoong** [comment]
应该是转换器转换的问题，请把Issue转移到PNX转换器下
