### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BrunoJaegerK** [PowerNukkitX/PowerNukkitX#868]
# 🐞 I found a bug

https://user-images.githubusercontent.com/99422811/208187025-fa201527-02e0-4e96-bf10-abc0211d3b8f.mp4

https://user-images.githubusercontent.com/99422811/208187063-552d3b15-378a-4b4b-b454-93bcdbfd3678.mp4

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Superice666** [comment]
It seems that's a plugin bug or sth else. We'll reopen this if you proivde more information about this. Thank you.
