### ISSUE TITLE
Bug in front and back third person swimming animation 

### ISSUE THREAD

**Issue by BrunoJaegerK** [PowerNukkitX/PowerNukkitX#869]
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by CoolLoong** [comment]
How do we reproduce it?

**Comment by CoolLoong** [comment]
I was unable to find a way to reproduce the problem and this issue needs more information to be resolved. If you have any questions you can reopen the issue.
