### ISSUE TITLE
force-gamemode bug

### ISSUE THREAD

**Issue by lt-name** [PowerNukkitX/PowerNukkitX#888]
# 🐞 错误汇报

👉 使用force-gamemode时，玩家重进服模式正常修改，但是部分规则没有正常更新

### ▶ 复现步骤
设置默认游戏模式为生存 开启force-gamemode
进入服务器 设置模式为创造
重进服务器，游戏模式变为生存，但是仍可飞行

### ✔ 预期行为
正常更新为生存模式

### ❌ 实际行为
更新为生存模式，但是仍可使用飞行

核心版本：1.19.50-r2 (git-fe14ae43b)
未安装任何插件

**Comment by smartcmd** [comment]
我试试能不能在观察者模式那个pr修了

**Comment by smartcmd** [comment]
感觉是adventureSettings的发送时机不对，试试改到客户端初始化之后再发试试

**Comment by smartcmd** [comment]
已在PR #873 修复
