### ISSUE TITLE
无法锻造

### ISSUE THREAD

**Issue by jlhsr** [PowerNukkitX/PowerNukkitX#898]
# 🐞 错误汇报👉 
![JVP_JKN9GI1K$509IM 8D9E](https://user-images.githubusercontent.com/22098995/209611742-77d410dc-d30a-477e-a598-42b9a431ee60.png)

### 💬 其他信息
PNX版本为 1.19.50 r3

**Comment by lt-name** [comment]
锻造台配方尚未注册
