### ISSUE TITLE
pnx-js插件的事件优先级无效

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#906]
# 🐞 错误汇报
通过下面的截图我们可以看到 NORMAL （正常）优先级的插件`NWeaponRe`执行在 HIGHEST （最高优先级）插件`NWeaponRe2`的前面。
而正常情况下HIGHEST应该优先于NORMAL执行
```
08:47:43 [INFO ] [NWeaponRe]: NORMAL
08:47:43 [INFO ] [NWeaponRe2]: HIGHEST
```
```ts
    declare class EventPriority {
        static LOWEST;
        static LOW;
        static NORMAL;
        static HIGH;
        static HIGHEST;
        static MONITOR;
    }
```

### 📸 截图或视频
![屏幕截图(330)](https://user-images.githubusercontent.com/48203962/209889880-41e2aa9b-051a-40db-9af2-95b0ce8dbc38.png)

### 💬 其他信息
 PowerNukkitX：**1.19.50-r3** 

插件包：[plugins.zip](https://github.com/PowerNukkitX/PowerNukkitX/files/10317071/plugins.zip)

**Comment by lt-name** [comment]
顺序是从低到高执行，这个顺序是正确的

**Comment by Superice666** [comment]
参阅：https://doc.powernukkitx.cn/zh-cn/plugin-dev/js/tutorial/%E4%BA%8B%E4%BB%B6%E7%9B%91%E5%90%AC.html
