### ISSUE TITLE
服务端权威方块破坏

### ISSUE THREAD

**Issue by Superice666** [PowerNukkitX/PowerNukkitX#910]
# ❇ 特性请求

由于Addons API无法满足自定义方块的工具破坏速度加成需要，加上某些瞬挖作弊在一些竞技性服务器出现，实现服务端权威方块破坏是必要的。
目前自定义方块在被原版物品挖掘时，服务端挖掘速度计算正确（但不灵活），会正确显示方块破碎的进度，但是客户端仍然认为速度等同于空手挖掘，所以等待很长一段时间时候才会发送破坏方块数据包，这导致自定义方块在被原版工具挖掘时会出现”挖不掉“的假象。
一些作弊客户端会发送一个挖掘数据包后紧接着发送方块破坏数据包达到瞬挖的效果，虽然服务器会对玩家持续挖掘的时间进行校验，但是作弊端可以通过挖掘时间转移的方法（先挖某个难以挖掘的方块一段时间，而后直接发送某个容易挖掘的方块的破坏数据包）来实现瞬间挖掘。

### 💬 你知道的其他信息

建议分为以下几部分分别完成：

- 添加设置自定义物品挖掘某个方块耗时的API和设置自定义方块被某一些工具挖掘耗时的API，而不是采取目前根据工具等级和方块硬度静态计算的极其不灵活的方案
- 如果玩家持续挖掘某一个方块超过这个方块的最大挖掘时间，当场破坏这个方块而不是静待客户端发送数据包
- 实现完全的服务端权威方块破坏协议，阻止作弊客户端的瞬间挖掘行为

**Comment by Blackjack200** [comment]
在玩家网络延迟过高的情况下会出现挖方块，但是没完全挖的情况，比较诡异

**Comment by Superice666** [comment]
https://user-images.githubusercontent.com/51087818/210127321-24ce1f9e-5610-4b63-9fd7-c10d45921f7d.mp4

**Comment by Superice666** [comment]
https://user-images.githubusercontent.com/51087818/210128367-717450dd-bfb3-4a56-874c-84c250c174c4.mp4
