### ISSUE TITLE
Can't light up signs font with glow ink sac

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#913]
# 🐞 Bug report

### ▶ Steps to Reproduce

1. Place a sign and write something 
2. Get a glow ink sac
3. Light the font up by clicking with the glow ink sac on the sign
4. Rejoin

### ✔ Expected Behavior
The font keep it glow after rejoining.

### ❌ Actual Behavior
The font lost it glow after rejoining.

### 📋 Debug information

* PowerNukkitX version: 1.19.50-r3

### 💬 Anything else we should know?
This bug did not occur in earlier versions.

**Comment by lt-name** [comment]
无法复现，请提供更多信息

**Comment by smartcmd** [comment]
translated: Unable to reproduce, please provide more information

**Comment by TraxTRL** [comment]
https://user-images.githubusercontent.com/56545793/210151556-22a75f3f-6760-4d50-b1db-5a82d272e459.mp4

**Comment by Superice666** [comment]
I cannot reproduce the bug either on 1.19.50-r3(git-e372e370b).

https://user-images.githubusercontent.com/51087818/210159354-2c15e00a-a379-4069-9236-3e4ca3f786e6.mp4

**Comment by lt-name** [comment]
1.19.50-r3 (git-6d259680c) and 1.19.50-r3 (git-8911f32) test normal
https://user-images.githubusercontent.com/45508179/210159385-782ab530-473a-4b38-8ede-468d3c973212.mp4
Maybe you should check if there is a plugin that modifies BlockEntitySign

**Comment by TraxTRL** [comment]
> 1.19.50-r3 (git-6d259680c) and 1.19.50-r3 (git-8911f32) test normal Maybe you should check if there is a plugin that modifies BlockEntitySign
> 
>  test.mp4

Thank you, this helped! We found the cause.
