### ISSUE TITLE
無法取消玩家飛行

### ISSUE THREAD

**Issue by Ootmnt150oO** [PowerNukkitX/PowerNukkitX#92]
# 🐞 错误汇报

先給一個生存玩家開啟飛行模式
之後再取消玩家飛行 如果玩家本來就在空中的話 他就會可以繼續飛行

### ✔ 预期行为

取消玩家飛行 要掉落到地上

### ❌ 实际行为

還能繼續飛行 但是只要取消了 就不能再飛行了

**Comment by Superice666** [comment]
您好，请问您使用什么方法取消了玩家的飞行呢？

**Comment by Ootmnt150oO** [comment]
插件的  event.getPlayer().setAllowFlight(false);

**Comment by Superice666** [comment]
此问题似乎是由于客户端bug导致的，由于客户端行为不一致，需要进一步确定问题范围。

**Comment by Superice666** [comment]
修复此问题需要实现服务端权威移动，工作量较大，您可以暂时通过快速切换玩家的游戏模式来解决此问题

**Comment by smartcmd** [comment]
AdventureSettings.set(Type.ALLOW_FLIGHT, false)方法只会阻止玩家切换到飞行模式
你还需要调用AdventureSettings.set(Type.FLYING, false)来取消玩家飞行状态
