### ISSUE TITLE
下界生成的岩浆不会更新

### ISSUE THREAD

**Issue by CoolLoong** [PowerNukkitX/PowerNukkitX#926]
# 🐞 错误汇报

下界生成的岩浆不会更新，不会流动
### 📸 截图或视频

![image](https://user-images.githubusercontent.com/69153398/210199954-8d96cb1d-5502-47d1-98a9-a5dea5e466fb.png)

**Comment by jlhsr** [comment]
+ terra生成的世界也是如此

**Comment by CoolLoong** [comment]
在最新master分支([b1e1195](https://github.com/PowerNukkitX/PowerNukkitX/commit/b1e119592283282d5d251b9793cc1968541c41df))中无法复现
