### ISSUE TITLE
if the player was in gm 3 and he moves to gm 1, then there are no items in the creative

### ISSUE THREAD

**Issue by CoolLoong** [PowerNukkitX/PowerNukkitX#930]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![image](https://user-images.githubusercontent.com/69153398/210799005-44ab158b-a5c1-4a7a-8586-d3e2a9a446f2.png)

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by smartcmd** [comment]
？？？

**Comment by CoolLoong** [comment]
无法复现
