### ISSUE TITLE
修改模式后部分地方没有修改

### ISSUE THREAD

**Issue by Rst307** [PowerNukkitX/PowerNukkitX#931]
# 🐞 错误汇报
从生存模式到创造模式后方块秒挖并且有掉落物(但是要使用对应工具)，背包未修改
从创造模式到生存模式后不显示血条背包也没有修改

**Comment by CoolLoong** [comment]
没太理解，能详细说明什么意思吗

**Comment by Rst307** [comment]
> 没有太理解，能详细说明什么意思吗
修改模式后有些界面没有改变

**Comment by CoolLoong** [comment]
你的PNX版本是什么，在最新版本中无法复现

**Comment by Rst307** [comment]
> 你的PNX版本是什么，在最新版本中无法复现

PowerNukkitX-master-502a5def0
pnx-cli下载最新的一个

**Comment by CoolLoong** [comment]
给出bug的触发方式

**Comment by Rst307** [comment]
> 给出bug的触发方式

就正常用gamemode指令

**Comment by smartcmd** [comment]
请卸载掉全部插件后再重试
这很有可能是由于插件的不正当操作引起的（）

**Comment by Rst307** [comment]
> 请卸载掉全部插件后再重试 这很有可能是由于插件的不正当操作引起的（）

有没有一种可能我连插件都没加你可以进我服务器看看
而且在设置里切换正常但是一用指令就不行
服务器地址:240e:3b5:1070:5c11:485c:1c06:b837:1508
端口:20081

**Comment by CoolLoong** [comment]
PNX不支持IPV6，你是怎么用IPV6开服的

**Comment by Rst307** [comment]
???我这个是waterdog+pnx的具体我也不清楚了

**Comment by Rst307** [comment]
> PNX不支持IPV6，你是怎么用IPV6开服的

我把waterdog那个关闭就好了但是我ipv6可以直接连接

**Comment by CoolLoong** [comment]
已经知道是waterdog和pnx的兼容性问题，后续会修复
