### ISSUE TITLE
Item.BELL returns a Tropical Fish 

### ISSUE THREAD

**Issue by KayllonDouglas** [PowerNukkitX/PowerNukkitX#947]
Exactly as the title says, for some reason the Item.BELL id returns a tropical fish to the player 

My code:
![Screenshot_2023-01-18-18-25-49-865_com termux](https://user-images.githubusercontent.com/76278156/213299146-f3bad0f9-bfe2-479c-8d79-1ec4e94e92d8.png)

The result:
![Screenshot_2023-01-18-18-21-05-324_com mojang minecraftpe](https://user-images.githubusercontent.com/76278156/213299411-35cf2651-8289-459c-875e-268a398ed5fe.jpg)

**Comment by CoolLoong** [comment]
Bell is a block. If you need to get it, use Item#getblock.Or you want clock
