### ISSUE TITLE
地狱问题

### ISSUE THREAD

**Issue by commandalan** [PowerNukkitX/PowerNukkitX#967]
玩家在地狱能放水（与原版不同）
玩家不能通过传送门返回对应的世界（有时候返回了却回到主城外围）

**Comment by smartcmd** [comment]
刷怪问题是mobplugin插件导致的，与核心无关

**Comment by CoolLoong** [comment]
在最新master分支([b1e1195](https://github.com/PowerNukkitX/PowerNukkitX/commit/b1e119592283282d5d251b9793cc1968541c41df))中无法复现
