### ISSUE TITLE
命令方块输出未完全屏蔽

### ISSUE THREAD

**Issue by PHEyejixHello** [PowerNukkitX/PowerNukkitX#968]
当我在游戏内输入/gamerule commandblockoutput false 后 ，使用命令方块循环执行/effect @a resistance 1 1 true 时，控制台依旧会输出给予效果提示

![image](https://user-images.githubusercontent.com/123708464/214993390-e08dd43d-6298-4636-b596-0b3714e44f7e.png)

**Comment by smartcmd** [comment]
请提供你的pnx版本

**Comment by smartcmd** [comment]
在最新pnx中应已修复
