### ISSUE TITLE
Can't put azalea in flower pots

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#969]
# 🐞 Bug report

### ▶ Steps to Reproduce

1. Get flower pots and azalea
2. Try to put the azalea in the pot
3. See result

### ✔ Expected Behavior
![Screenshot_20230127-131416](https://user-images.githubusercontent.com/56545793/215086002-e165947a-8cf4-4f0f-8f13-79b7634468b9.png)
Can put it in it.

### ❌ Actual Behavior
![Screenshot_20230127-131952](https://user-images.githubusercontent.com/56545793/215086037-0cf15184-a2ac-40b1-875c-0b9bc8e9b521.png)
Can't put it in it.

**Comment by smartcmd** [comment]
Fixed
