### ISSUE TITLE
DEPENDENCY ERROR

### ISSUE THREAD

**Issue by Verciak** [PowerNukkitX/PowerNukkitX#991]
# 🐞 I found a bug

### ✔ Expected Behavior

dependency repair

### ❌ MY POM.XML

    <groupId>pl.vertty.nukkit</groupId>
    <artifactId>onehard_Core</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20220924</version>
        </dependency>
        <dependency>
            <groupId>cn.powernukkitx</groupId>
            <artifactId>powernukkitx</artifactId>
            <version>1.19.50-r3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.10.2</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.9</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.12.8</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>

### 💢 Crash Dump, Stack Trace and Other Files

Could not find artifact org.powernukkit.bedrock.network:raknet:pom:1.6.28-PNX.5 in central (https://repo.maven.apache.org/maven2)

Could not find artifact com.dfsek.terra:Terra:pom:6.2.0+BETA in central (https://repo.maven.apache.org/maven2)

Could not find artifact cn.powernukkitx:libdeflate-java:pom:0.0.2-PNX in central (https://repo.maven.apache.org/maven2)

**Comment by Superice666** [comment]
If you encounter the same problem, you can try this:
```xml
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    <dependency>
        <groupId>cn.powernukkitx</groupId>
        <artifactId>powernukkitx</artifactId>
        <version>-SNAPSHOT</version>
    </dependency>
```
This issue will be closed after the release of version 1.19.60-r1.
